/* ============================================
   DevKit HQ — Shared JS
   Nav, Theme, i18n, Utilities
   ============================================ */

// ===== i18n Config =====
const LANGUAGES = [
  { code: 'zh', name: '中文', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'ja', name: '日本語', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'ru', name: 'Русский', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'pt', name: 'Português', nativeName: 'Português (BR)', flag: '🇧🇷' },
  { code: 'es', name: 'Español', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ar', name: 'العربية', nativeName: 'العربية', flag: '🇸🇦', rtl: true },
  { code: 'hi', name: 'हिन्दी', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'th', name: 'ไทย', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Tiếng Việt', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'tr', name: 'Türkçe', nativeName: 'Türkçe', flag: '🇹🇷' }
];

// ===== i18n Data =====
const I18N = {
  zh: {
    // Nav
    navHome: '首页',
    navImageTools: '图片工具',
    navDevTools: '开发工具',
    navDomain: '域名查询',
    // Homepage
    heroBadge: '12 款免费在线工具',
    heroTitle: '图片与代码工具<br><span>都在浏览器里完成</span>',
    heroSub: '隐私优先，所有数据在本地处理。开发者与设计师的在线工具箱。',
    heroCTA: '开始使用',
    heroGithub: 'GitHub',
    secImage: '图片工具',
    secImageSub: '压缩、转换、水印、调色 — 全部在 Canvas 本地处理',
    secDev: '开发工具',
    secDevSub: '格式化、编解码、时间戳 — 程序员日常必备',
    descCompress: '智能压缩 JPEG / PNG / WebP，批量处理，本地完成',
    descConvert: '图片格式互转 JPEG ↔ PNG ↔ WebP，可调质量与尺寸',
    descResize: '自由裁剪和缩放图片，可视化操作',
    descWatermark: '添加文字或图片水印，保护你的作品',
    descImgBase64: '将图片编码为 Base64 文本，一键复制',
    descPalette: '上传图片提取主色调，生成配色方案',
    descJson: '粘贴 JSON 一键美化，错误自动标注行号',
    descBase64: '文本 ↔ Base64 编解码，支持中文',
    descUrl: 'URL 编解码，encodeURI / decodeURI',
    descTimestamp: 'Unix 时间戳 ↔ 人类可读日期时间互转',
    descMarkdown: '实时预览 Markdown 渲染效果，分栏编辑',
    descDomain: '查询域名 WHOIS 信息，判断是否可注册',
    toolCompress: '图片压缩',
    toolConvert: '格式转换',
    toolResize: '裁剪缩放',
    toolWatermark: '水印工具',
    toolImgBase64: '图片转 Base64',
    toolPalette: '色彩提取',
    toolJson: 'JSON 格式化',
    toolBase64: 'Base64 编解码',
    toolUrl: 'URL 编解码',
    toolTimestamp: '时间戳转换',
    toolMarkdown: 'Markdown 预览',
    toolDomain: '域名查询',
    taglineCompress: '智能压缩 JPEG / PNG / WebP，所有处理在浏览器本地完成',
    taglineConvert: 'JPEG / PNG / WebP 互转，可调质量与尺寸',
    taglineResize: '可视化裁剪图片，支持锁定比例与预设尺寸',
    taglineWatermark: '添加文字或图片水印，保护你的作品',
    taglineImgBase64: '将图片编码为 Base64 文本，可直接嵌入 HTML/CSS',
    taglinePalette: '上传图片，自动提取主色调与配色方案',
    taglineJson: '粘贴 JSON 一键美化或压缩，错误自动标注行号，支持一键复制',
    taglineBase64: '文本 ↔ Base64 在线编解码，支持中文等 Unicode 字符',
    taglineUrl: 'URL 编码与解码，使用标准 encodeURIComponent / decodeURIComponent',
    taglineTimestamp: 'Unix 时间戳 ↔ 日期时间互转，支持秒/毫秒自动识别',
    taglineMarkdown: '实时编辑预览 Markdown，支持 GitHub Flavored Markdown',
    taglineDomain: '查询域名 WHOIS 信息，判断能否注册',
    footerImageTools: '图片工具',
    footerDevTools: '开发工具',
    footerAbout: '关于',
    footerAboutText: '为开发者和设计师打造的免费在线工具箱。所有工具均在浏览器本地运行，数据不会上传到任何服务器。',
    footerBottom: '© 2026 DevKit HQ · 浏览器本地处理 · 隐私优先',
    footerMadeWith: 'Made with',
    backHome: '← 返回首页',
    footer: '© 2026 DevKit HQ · 所有工具均在浏览器本地运行 · 隐私安全',
    statTools: '款工具',
    statLocal: '浏览器本地',
    statPrivacy: '数据上传',
    themeDark: '暗色模式',
    themeLight: '亮色模式',
    copied: '已复制到剪贴板',
    error: '操作失败，请重试',
    processing: '处理中',
    done: '完成',
    // Page title
    pageTitle: 'DevKit HQ — 免费在线图片与代码工具',
    pageTitleCompress: '图片压缩 — DevKit HQ',
    pageTitleConvert: '格式转换 — DevKit HQ',
    pageTitleResize: '裁剪缩放 — DevKit HQ',
    pageTitleWatermark: '水印工具 — DevKit HQ',
    pageTitleImgBase64: '图片转 Base64 — DevKit HQ',
    pageTitlePalette: '色彩提取 — DevKit HQ',
    pageTitleJson: 'JSON 格式化 — DevKit HQ',
    pageTitleBase64: 'Base64 编解码 — DevKit HQ',
    pageTitleUrl: 'URL 编解码 — DevKit HQ',
    pageTitleTimestamp: '时间戳转换 — DevKit HQ',
    pageTitleMarkdown: 'Markdown 预览 — DevKit HQ',
    pageTitleDomain: '域名查询 — DevKit HQ',
    adPlaceholder: '广告位',
    dropzoneTitle: '拖拽或点击上传图片',
    dropzoneSub: '或点击选择文件',
    selectFile: '选择文件',
    feedback: '反馈建议',
    clear: '清空',
    close: '关闭',
    copyResult: '复制结果',
    noContentToCopy: '没有可复制的内容',
    unsupportedFormat: '不支持的格式',
    exportFail: '导出失败',
    downloadComplete: '下载完成',
    resetImage: '重新选择',
    original: '原始',
    originalSize: '原始尺寸',
    maxWidth: '最大宽度',
    quality: '质量',
    formatLabel: '格式',
    preview: '预览',
    encode: '编码',
    decode: '解码',
    swap: '交换',
    startOver: '重新开始',
    downloadAll: '下载全部',
    save: '保存',
    cancel: '取消',
    choose: '选择',
    copy: '复制',
    paste: '粘贴',
    loadSample: '加载示例',
    color: '颜色',
    opacity: '透明度',
    scale: '缩放',
    fontSize: '字号',
    dimensions: '尺寸',
    aspectRatio: '比例',
    position: '位置',
    fileName: '文件名',
    imageSize: '图片尺寸',
    clickToCopy: '点击复制',
    compressAll: '全部压缩',
    fileCount: '个文件',
    compressed: '已压缩',
    beforeAfterCompare: '压缩前后对比',
    compressedSize: '压缩后',
    downloadCompressed: '下载压缩图片',
    compressDropzoneSub: '支持 JPEG / PNG / WebP · 单张最大 20MB',
    imageCountUnit: '张',
    packing: '正在打包...',
    packingFailed: '打包失败',
    converted: '转换后',
    outputFormat: '输出格式',
    downloadConverted: '下载转换后图片',
    convertDropzoneSub: '支持 JPEG / PNG / WebP · 最大 20MB',
    resizeRatio: '比例：',
    resizeFree: '自由',
    resizeDim: '尺寸：',
    resizeSwapTitle: '交换宽高',
    resizePreset: '预设：',
    resizeResetSelection: '重置选区',
    resizeDownload: '下载裁剪结果',
    resizeCropArea: '裁剪区域：',
    resizeOrigSize: '原始尺寸：',
    resizeDragHint: '拖拽选区四角或边缘调整',
    resizeDropzoneSub: '支持 JPEG / PNG / WebP · 最大 20MB',
    wmTabText: '文字水印',
    wmTabLogo: 'Logo 水印',
    wmWatermarkText: '文字',
    wmTextPlaceholder: '输入水印文字',
    wmFontSize: '字号',
    wmColor: '颜色',
    wmOpacity: '透明度',
    wmLogoSelect: '选择 Logo 图片',
    wmScale: '缩放',
    wmPosition: '位置',
    wmRechoose: '重新选择图片',
    wmDownloadResult: '下载带水印图片',
    wmNoText: '请输入水印文字',
    wmNoLogo: '请先选择 Logo 图片',
    wmDropzoneSub: '支持 JPEG / PNG / WebP · 最大 20MB',
    imgFormat: '格式：',
    imgSize: '原始大小：',
    imgBase64Data: 'Base64 数据',
    imgHtmlTag: 'HTML img 标签',
    imgCssBg: 'CSS background-image',
    imgCopyBtn: '复制 Base64',
    imgSelectImage: '请选择图片文件',
    imgMaxSize: '文件最大 10MB',
    imgDropzoneSub: '支持 JPEG / PNG / WebP / GIF / SVG · 最大 10MB',
    imgPreviewAlt: '预览图片',
    paletteFileName: '文件名：',
    paletteDimensions: '尺寸：',
    paletteDominant: '主色调：',
    paletteEmptyState: '无法提取颜色，请尝试其他图片',
    paletteColorsCount: '个',
    paletteClickCopy: '点击复制',
    paletteCopied: '已复制!',
    paletteDominantSuffix: '主色调',
    paletteDropzoneSub: '支持 JPEG / PNG / WebP · 最大 20MB',
    jsonFormatBtn: '格式化',
    jsonMinifyBtn: '压缩',
    jsonWaiting: '等待输入...',
    jsonPlaceholder: '在此粘贴 JSON...',
    jsonLines: '行',
    jsonChars: '字符',
    jsonSize: '大小',
    jsonErrorLine: '行',
    jsonClearBtn: '清空',
    b64InputLabel: '输入文本',
    b64InputPlaceholder: '在此输入要编码的文本，或粘贴已编码的 Base64 字符串进行解码...',
    b64OutputLabel: '输出结果',
    b64OutputPlaceholder: '结果将显示在这里...',
    b64EncodeFail: '编码失败:',
    b64DecodeFail: '解码失败: 请检查输入是否为有效的 Base64 字符串',
    urlInputLabel: '输入文本',
    urlInputPlaceholder: '在此输入要编码的文本或 URL，或粘贴已编码的 URL 字符串进行解码...',
    urlOutputLabel: '输出结果',
    urlOutputPlaceholder: '结果将显示在这里...',
    urlEncodeFull: '编码完整 URI (encodeURI)',
    urlEncodeFail: '编码失败:',
    urlDecodeFail: '解码失败: 请检查输入是否为有效的 URL 编码字符串',
    tsLiveHint: '当前北京时间 · 实时更新 · 点击时间戳复制',
    tsInputPlaceholder: '输入 Unix 时间戳，如 1716500000（秒）或 1716500000000（毫秒）',
    tsConvertBtn: '转换',
    tsNowBtn: '当前时间',
    tsBeijing: '北京时间 (UTC+8)',
    tsUTC: 'UTC 时间',
    tsISO: 'ISO 8601 格式',
    tsRelative: '相对时间',
    tsReverseDivider: '反向转换 · 日期 → 时间戳',
    tsDate: '日期',
    tsTime: '时间',
    tsResult: '结果',
    tsCopyReverse: '复制时间戳',
    tsReverseHint: '提示：选择日期和时间后自动计算',
    tsInvalid: '请输入有效的数字时间戳',
    tsInvalidDate: '无效的时间戳',
    tsSelectDate: '请先选择有效日期',
    tsSecAgo: '秒前',
    tsMinAgo: '分钟前',
    tsHrAgo: '小时前',
    tsDayAgo: '天前',
    tsMonAgo: '个月前',
    tsYrAgo: '年前',
    tsSecLater: '秒后',
    tsMinLater: '分钟后',
    tsHrLater: '小时后',
    tsDayLater: '天后',
    tsMonLater: '个月后',
    tsYrLater: '年后',
    mdCopy: '复制 Markdown',
    mdClear: '清空',
    mdSample: '加载示例',
    mdGfmHint: '支持 GFM 语法',
    mdEditorLabel: 'Markdown',
    mdEditorBadge: '编辑',
    mdPreviewLabel: 'Preview',
    mdPreviewBadge: '预览',
    mdEditorPlaceholder: '在此输入 Markdown...',
    mdEmptyState: '在左侧输入 Markdown，这里实时预览',
    mdRenderError: '渲染错误:',
    dlInputPlaceholder: '输入域名，如 example.com',
    dlSearchBtn: '查询',
    dlExamples: '试试:',
    dlNotRegistered: '未注册示例',
    dlQuerying: '查询中...',
    dlFail: '查询失败',
    dlAvailable: '可注册 ✨',
    dlRegistered: '已注册',
    dlUnknown: '未知',
    dlSuffix: '后缀',
    dlRegistrar: '注册商',
    dlStatus: '状态',
    dlCreated: '创建日期',
    dlExpires: '过期日期',
    dlUpdated: '最后更新',
    dlDNS: 'DNS 服务器',
    dlNetworkError: '网络错误:',
  },
  en: {
    navHome: 'Home',
    navImageTools: 'Image Tools',
    navDevTools: 'Dev Tools',
    navDomain: 'Domain Lookup',
    heroBadge: '12 Free Online Tools',
    heroTitle: 'Image &amp; code tools<br><span>all in your browser</span>',
    heroSub: 'Privacy-first. Everything runs locally. The online toolbox for developers and designers.',
    heroCTA: 'Get Started',
    heroGithub: 'GitHub',
    secImage: 'Image Tools',
    secImageSub: 'Compress, convert, watermark, extract palettes — all via Canvas',
    secDev: 'Dev Tools',
    secDevSub: 'Format, encode, decode — daily essentials for developers',
    descCompress: 'Smart compression for JPEG / PNG / WebP. Batch processing, local.',
    descConvert: 'Convert between JPEG, PNG, WebP with quality and size controls.',
    descResize: 'Crop and resize images with an interactive visual editor.',
    descWatermark: 'Add text or image watermarks to protect your work.',
    descImgBase64: 'Encode images to Base64 text. One-click copy.',
    descPalette: 'Extract dominant colors from any image. Generate palettes.',
    descJson: 'Paste messy JSON, get instant formatting with error highlighting.',
    descBase64: 'Encode and decode text to/from Base64. Supports Unicode.',
    descUrl: 'URL encode and decode. encodeURI / decodeURI.',
    descTimestamp: 'Convert between Unix timestamps and human-readable dates.',
    descMarkdown: 'Live Markdown preview with split-pane editing.',
    descDomain: 'Look up WHOIS info for any domain. Check availability.',
    toolCompress: 'Image Compress',
    toolConvert: 'Format Convert',
    toolResize: 'Crop & Resize',
    toolWatermark: 'Watermark',
    toolImgBase64: 'Image to Base64',
    toolPalette: 'Color Palette',
    toolJson: 'JSON Formatter',
    toolBase64: 'Base64 Codec',
    toolUrl: 'URL Codec',
    toolTimestamp: 'Timestamp',
    toolMarkdown: 'Markdown Preview',
    toolDomain: 'Domain Lookup',
    taglineCompress: 'Smart JPEG / PNG / WebP compression. All processing done locally in your browser.',
    taglineConvert: 'Convert between JPEG, PNG, WebP formats with quality and size controls.',
    taglineResize: 'Visual crop tool with aspect ratio lock and preset sizes.',
    taglineWatermark: 'Add text or image watermarks to protect your work.',
    taglineImgBase64: 'Encode images to Base64 text for embedding in HTML/CSS.',
    taglinePalette: 'Upload an image to automatically extract dominant colors and palettes.',
    taglineJson: 'Paste JSON, get instant formatting or minification with error line highlighting. One-click copy.',
    taglineBase64: 'Online Base64 encoder and decoder. Supports Unicode characters.',
    taglineUrl: 'URL encode and decode. Standard encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Convert between Unix timestamps and dates. Auto-detects seconds/milliseconds.',
    taglineMarkdown: 'Live Markdown editor with split-pane preview. GitHub Flavored Markdown.',
    taglineDomain: 'Look up WHOIS info for any domain. Check registration availability.',
    footerImageTools: 'Image Tools',
    footerDevTools: 'Dev Tools',
    footerAbout: 'About',
    footerAboutText: 'A free online toolbox for developers and designers. All tools run locally in your browser — no data is ever uploaded.',
    footerBottom: '© 2026 DevKit HQ · Local processing · Privacy first',
    footerMadeWith: 'Made with',
    backHome: '← Back to Home',
    footer: '© 2026 DevKit HQ · All tools run locally in your browser · Privacy first',
    statTools: 'Tools',
    statLocal: 'Local Processing',
    statPrivacy: 'No Data Upload',
    themeDark: 'Dark mode',
    themeLight: 'Light mode',
    copied: 'Copied to clipboard',
    error: 'Something went wrong. Please try again.',
    processing: 'Processing...',
    done: 'Done',
    pageTitle: 'DevKit HQ — Free Online Tools for Images & Code',
    pageTitleCompress: 'Image Compress — DevKit HQ',
    pageTitleConvert: 'Format Convert — DevKit HQ',
    pageTitleResize: 'Crop & Resize — DevKit HQ',
    pageTitleWatermark: 'Watermark — DevKit HQ',
    pageTitleImgBase64: 'Image to Base64 — DevKit HQ',
    pageTitlePalette: 'Color Palette — DevKit HQ',
    pageTitleJson: 'JSON Formatter — DevKit HQ',
    pageTitleBase64: 'Base64 Codec — DevKit HQ',
    pageTitleUrl: 'URL Codec — DevKit HQ',
    pageTitleTimestamp: 'Timestamp Converter — DevKit HQ',
    pageTitleMarkdown: 'Markdown Preview — DevKit HQ',
    pageTitleDomain: 'Domain Lookup — DevKit HQ',
    adPlaceholder: 'Advertisement',
    dropzoneTitle: 'Drag & drop or click to upload',
    dropzoneSub: 'or click to select files',
    selectFile: 'Select File',
    feedback: 'Feedback',
    clear: 'Clear',
    close: 'Close',
    copyResult: 'Copy Result',
    noContentToCopy: 'Nothing to copy',
    unsupportedFormat: 'Unsupported format',
    exportFail: 'Export failed',
    downloadComplete: 'Download complete',
    resetImage: 'Reselect',
    original: 'Original',
    originalSize: 'Original size',
    maxWidth: 'Max width',
    quality: 'Quality',
    formatLabel: 'Format',
    preview: 'Preview',
    encode: 'Encode',
    decode: 'Decode',
    swap: 'Swap',
    startOver: 'Start over',
    downloadAll: 'Download all',
    save: 'Save',
    cancel: 'Cancel',
    choose: 'Choose',
    copy: 'Copy',
    paste: 'Paste',
    loadSample: 'Load sample',
    color: 'Color',
    opacity: 'Opacity',
    scale: 'Scale',
    fontSize: 'Font size',
    dimensions: 'Dimensions',
    aspectRatio: 'Aspect ratio',
    position: 'Position',
    fileName: 'File name',
    imageSize: 'Image size',
    clickToCopy: 'Click to copy',
    compressAll: 'Compress all',
    fileCount: 'files',
    compressed: 'Compressed',
    beforeAfterCompare: 'Before / After',
    compressedSize: 'Compressed',
    downloadCompressed: 'Download compressed',
    compressDropzoneSub: 'Supports JPEG / PNG / WebP · Max 20MB each',
    imageCountUnit: '',
    packing: 'Packing...',
    packingFailed: 'Pack failed',
    converted: 'Converted',
    outputFormat: 'Output format',
    downloadConverted: 'Download converted',
    convertDropzoneSub: 'Supports JPEG / PNG / WebP · Max 20MB',
    resizeRatio: 'Ratio:',
    resizeFree: 'Free',
    resizeDim: 'Size:',
    resizeSwapTitle: 'Swap width/height',
    resizePreset: 'Presets:',
    resizeResetSelection: 'Reset selection',
    resizeDownload: 'Download cropped',
    resizeCropArea: 'Crop area:',
    resizeOrigSize: 'Original size:',
    resizeDragHint: 'Drag corners or edges to adjust',
    resizeDropzoneSub: 'Supports JPEG / PNG / WebP · Max 20MB',
    wmTabText: 'Text watermark',
    wmTabLogo: 'Logo watermark',
    wmWatermarkText: 'Text',
    wmTextPlaceholder: 'Enter watermark text',
    wmFontSize: 'Font size',
    wmColor: 'Color',
    wmOpacity: 'Opacity',
    wmLogoSelect: 'Select logo image',
    wmScale: 'Scale',
    wmPosition: 'Position',
    wmRechoose: 'Reselect image',
    wmDownloadResult: 'Download watermarked',
    wmNoText: 'Please enter watermark text',
    wmNoLogo: 'Please select a logo image first',
    wmDropzoneSub: 'Supports JPEG / PNG / WebP · Max 20MB',
    imgFormat: 'Format:',
    imgSize: 'Original size:',
    imgBase64Data: 'Base64 data',
    imgHtmlTag: 'HTML img tag',
    imgCssBg: 'CSS background-image',
    imgCopyBtn: 'Copy Base64',
    imgSelectImage: 'Please select an image file',
    imgMaxSize: 'File max 10MB',
    imgDropzoneSub: 'Supports JPEG / PNG / WebP / GIF / SVG · Max 10MB',
    imgPreviewAlt: 'Preview image',
    paletteFileName: 'File name:',
    paletteDimensions: 'Dimensions:',
    paletteDominant: 'Dominant color:',
    paletteEmptyState: 'No colors found. Try another image.',
    paletteColorsCount: 'colors',
    paletteClickCopy: 'Click to copy',
    paletteCopied: 'Copied!',
    paletteDominantSuffix: 'dominant',
    paletteDropzoneSub: 'Supports JPEG / PNG / WebP · Max 20MB',
    jsonFormatBtn: 'Format',
    jsonMinifyBtn: 'Minify',
    jsonWaiting: 'Waiting for input...',
    jsonPlaceholder: 'Paste JSON here...',
    jsonLines: 'lines',
    jsonChars: 'chars',
    jsonSize: 'size',
    jsonErrorLine: 'line',
    jsonClearBtn: 'Clear',
    b64InputLabel: 'Input text',
    b64InputPlaceholder: 'Enter text to encode, or paste Base64 string to decode...',
    b64OutputLabel: 'Output result',
    b64OutputPlaceholder: 'Result will appear here...',
    b64EncodeFail: 'Encode failed:',
    b64DecodeFail: 'Decode failed: invalid Base64 string',
    urlInputLabel: 'Input text',
    urlInputPlaceholder: 'Enter text or URL to encode, or paste encoded URL to decode...',
    urlOutputLabel: 'Output result',
    urlOutputPlaceholder: 'Result will appear here...',
    urlEncodeFull: 'Encode full URI (encodeURI)',
    urlEncodeFail: 'Encode failed:',
    urlDecodeFail: 'Decode failed: invalid URL-encoded string',
    tsLiveHint: 'Live Beijing time · Updates every second · Click timestamp to copy',
    tsInputPlaceholder: 'Enter Unix timestamp, e.g. 1716500000 (s) or 1716500000000 (ms)',
    tsConvertBtn: 'Convert',
    tsNowBtn: 'Now',
    tsBeijing: 'Beijing Time (UTC+8)',
    tsUTC: 'UTC Time',
    tsISO: 'ISO 8601 Format',
    tsRelative: 'Relative time',
    tsReverseDivider: 'Reverse · Date → Timestamp',
    tsDate: 'Date',
    tsTime: 'Time',
    tsResult: 'Result',
    tsCopyReverse: 'Copy timestamp',
    tsReverseHint: 'Tip: auto-calculates when date/time is selected',
    tsInvalid: 'Please enter a valid numeric timestamp',
    tsInvalidDate: 'Invalid timestamp',
    tsSelectDate: 'Please select a valid date first',
    tsSecAgo: 'sec ago',
    tsMinAgo: 'min ago',
    tsHrAgo: 'hr ago',
    tsDayAgo: 'days ago',
    tsMonAgo: 'mo ago',
    tsYrAgo: 'yr ago',
    tsSecLater: 'sec later',
    tsMinLater: 'min later',
    tsHrLater: 'hr later',
    tsDayLater: 'days later',
    tsMonLater: 'mo later',
    tsYrLater: 'yr later',
    mdCopy: 'Copy Markdown',
    mdClear: 'Clear',
    mdSample: 'Load sample',
    mdGfmHint: 'Supports GFM syntax',
    mdEditorLabel: 'Markdown',
    mdEditorBadge: 'Edit',
    mdPreviewLabel: 'Preview',
    mdPreviewBadge: 'Preview',
    mdEditorPlaceholder: 'Enter Markdown here...',
    mdEmptyState: 'Enter Markdown on the left to see a live preview here',
    mdRenderError: 'Render error:',
    dlInputPlaceholder: 'Enter domain, e.g. example.com',
    dlSearchBtn: 'Lookup',
    dlExamples: 'Try:',
    dlNotRegistered: 'Available examples',
    dlQuerying: 'Looking up...',
    dlFail: 'Lookup failed',
    dlAvailable: 'Available ✨',
    dlRegistered: 'Registered',
    dlUnknown: 'Unknown',
    dlSuffix: 'TLD',
    dlRegistrar: 'Registrar',
    dlStatus: 'Status',
    dlCreated: 'Created',
    dlExpires: 'Expires',
    dlUpdated: 'Updated',
    dlDNS: 'DNS Servers',
    dlNetworkError: 'Network error:',
  },
  ja: {
    navHome: 'ホーム',
    navImageTools: '画像ツール',
    navDevTools: '開発ツール',
    navDomain: 'ドメイン検索',
    heroBadge: '12の無料オンラインツール',
    heroTitle: '画像とコードのツール<br><span>すべてブラウザで完結</span>',
    heroSub: 'プライバシー最優先。すべてのデータはローカルで処理されます。開発者とデザイナーのためのオンラインツールボックス。',
    heroCTA: 'はじめる',
    heroGithub: 'GitHub',
    secImage: '画像ツール',
    secImageSub: '圧縮、変換、透かし、パレット抽出 — すべてCanvasで処理',
    secDev: '開発ツール',
    secDevSub: 'フォーマット、エンコード、デコード — 開発者の日常必須ツール',
    descCompress: 'JPEG / PNG / WebPのスマート圧縮。バッチ処理、ローカル完結。',
    descConvert: 'JPEG、PNG、WebP間の相互変換。品質とサイズ調整可能。',
    descResize: 'インタラクティブなビジュアルエディタで画像を切り抜き・リサイズ。',
    descWatermark: 'テキストまたは画像の透かしを追加して作品を保護。',
    descImgBase64: '画像をBase64テキストにエンコード。ワンクリックでコピー。',
    descPalette: '画像から主要な色を抽出。パレットを生成。',
    descJson: 'JSONを貼り付けるだけで即座に整形。エラー行をハイライト。',
    descBase64: 'テキストとBase64の相互エンコード・デコード。Unicode対応。',
    descUrl: 'URLエンコードとデコード。encodeURI / decodeURI。',
    descTimestamp: 'Unixタイムスタンプと日時の相互変換。',
    descMarkdown: '分割ペイン編集でMarkdownをリアルタイムプレビュー。',
    descDomain: 'ドメインのWHOIS情報を検索。登録可否を確認。',
    toolCompress: '画像圧縮',
    toolConvert: '形式変換',
    toolResize: '切り抜き・リサイズ',
    toolWatermark: '透かし',
    toolImgBase64: '画像→Base64',
    toolPalette: 'カラーパレット',
    toolJson: 'JSONフォーマッタ',
    toolBase64: 'Base64コーデック',
    toolUrl: 'URLコーデック',
    toolTimestamp: 'タイムスタンプ',
    toolMarkdown: 'Markdownプレビュー',
    toolDomain: 'ドメイン検索',
    taglineCompress: 'JPEG / PNG / WebPのスマート圧縮。すべての処理はブラウザ内でローカルに実行。',
    taglineConvert: 'JPEG、PNG、WebP形式間の変換。品質とサイズのコントロール付き。',
    taglineResize: 'アスペクト比ロックとプリセットサイズ付きのビジュアルクロップツール。',
    taglineWatermark: 'テキストまたは画像の透かしを追加して作品を保護。',
    taglineImgBase64: '画像をBase64テキストにエンコード。HTML/CSSに埋め込み可能。',
    taglinePalette: '画像をアップロードして主要な色とパレットを自動抽出。',
    taglineJson: 'JSONを貼り付けて即座に整形または圧縮。エラー行のハイライト付き。ワンクリックコピー。',
    taglineBase64: 'オンラインBase64エンコーダ・デコーダ。Unicode文字対応。',
    taglineUrl: 'URLエンコードとデコード。標準のencodeURIComponent / decodeURIComponent。',
    taglineTimestamp: 'Unixタイムスタンプと日時の変換。秒/ミリ秒を自動検出。',
    taglineMarkdown: '分割ペインでリアルタイムMarkdown編集。GitHub Flavored Markdown対応。',
    taglineDomain: 'ドメインのWHOIS情報を検索。登録の可否を確認。',
    footerImageTools: '画像ツール',
    footerDevTools: '開発ツール',
    footerAbout: '概要',
    footerAboutText: '開発者とデザイナーのための無料オンラインツールボックス。すべてのツールはブラウザ内でローカルに実行され、データがアップロードされることはありません。',
    footerBottom: '© 2026 DevKit HQ · ローカル処理 · プライバシー最優先',
    footerMadeWith: 'Made with',
    backHome: '← ホームに戻る',
    footer: '© 2026 DevKit HQ · すべてのツールはブラウザ内でローカルに実行 · プライバシー安全',
    statTools: 'ツール',
    statLocal: 'ローカル処理',
    statPrivacy: 'データアップロードなし',
    themeDark: 'ダークモード',
    themeLight: 'ライトモード',
    copied: 'クリップボードにコピーしました',
    error: 'エラーが発生しました。もう一度お試しください。',
    processing: '処理中...',
    done: '完了',
    pageTitle: 'DevKit HQ — 無料オンライン画像・コードツール',
    pageTitleCompress: '画像圧縮 — DevKit HQ',
    pageTitleConvert: '形式変換 — DevKit HQ',
    pageTitleResize: '切り抜き・リサイズ — DevKit HQ',
    pageTitleWatermark: '透かし — DevKit HQ',
    pageTitleImgBase64: '画像→Base64 — DevKit HQ',
    pageTitlePalette: 'カラーパレット — DevKit HQ',
    pageTitleJson: 'JSONフォーマッタ — DevKit HQ',
    pageTitleBase64: 'Base64コーデック — DevKit HQ',
    pageTitleUrl: 'URLコーデック — DevKit HQ',
    pageTitleTimestamp: 'タイムスタンプ変換 — DevKit HQ',
    pageTitleMarkdown: 'Markdownプレビュー — DevKit HQ',
    pageTitleDomain: 'ドメイン検索 — DevKit HQ',
  },
  ko: {
    navHome: '홈',
    navImageTools: '이미지 도구',
    navDevTools: '개발 도구',
    navDomain: '도메인 조회',
    heroBadge: '12가지 무료 온라인 도구',
    heroTitle: '이미지 및 코드 도구<br><span>모두 브라우저에서</span>',
    heroSub: '개인정보 보호 우선. 모든 데이터는 로컬에서 처리됩니다. 개발자와 디자이너를 위한 온라인 도구 모음.',
    heroCTA: '시작하기',
    heroGithub: 'GitHub',
    secImage: '이미지 도구',
    secImageSub: '압축, 변환, 워터마크, 팔레트 추출 — 모두 Canvas에서 처리',
    secDev: '개발 도구',
    secDevSub: '포맷, 인코딩, 디코딩 — 개발자 필수 도구',
    descCompress: 'JPEG / PNG / WebP 스마트 압축. 배치 처리, 로컬 완료.',
    descConvert: 'JPEG, PNG, WebP 간 상호 변환. 품질 및 크기 조정 가능.',
    descResize: '대화형 비주얼 편집기로 이미지 자르기 및 크기 조정.',
    descWatermark: '텍스트 또는 이미지 워터마크를 추가하여 작업물 보호.',
    descImgBase64: '이미지를 Base64 텍스트로 인코딩. 원클릭 복사.',
    descPalette: '이미지에서 주요 색상 추출. 팔레트 생성.',
    descJson: 'JSON을 붙여넣으면 즉시 포맷팅. 오류 라인 하이라이트.',
    descBase64: '텍스트 ↔ Base64 인코딩/디코딩. 유니코드 지원.',
    descUrl: 'URL 인코딩 및 디코딩. encodeURI / decodeURI.',
    descTimestamp: 'Unix 타임스탬프 ↔ 읽기 쉬운 날짜 시간 변환.',
    descMarkdown: '분할 창 편집으로 Markdown 실시간 미리보기.',
    descDomain: '도메인 WHOIS 정보 조회. 등록 가능 여부 확인.',
    toolCompress: '이미지 압축',
    toolConvert: '형식 변환',
    toolResize: '자르기 및 크기 조정',
    toolWatermark: '워터마크',
    toolImgBase64: '이미지→Base64',
    toolPalette: '색상 팔레트',
    toolJson: 'JSON 포맷터',
    toolBase64: 'Base64 코덱',
    toolUrl: 'URL 코덱',
    toolTimestamp: '타임스탬프',
    toolMarkdown: 'Markdown 미리보기',
    toolDomain: '도메인 조회',
    taglineCompress: '스마트 JPEG / PNG / WebP 압축. 모든 처리는 브라우저에서 로컬로 실행됩니다.',
    taglineConvert: 'JPEG, PNG, WebP 형식 간 변환. 품질 및 크기 제어 기능.',
    taglineResize: '화면 비율 잠금 및 사전 설정 크기가 포함된 비주얼 자르기 도구.',
    taglineWatermark: '텍스트 또는 이미지 워터마크를 추가하여 작업물 보호.',
    taglineImgBase64: 'HTML/CSS에 삽입할 수 있도록 이미지를 Base64 텍스트로 인코딩.',
    taglinePalette: '이미지를 업로드하여 주요 색상과 팔레트를 자동으로 추출.',
    taglineJson: 'JSON을 붙여넣으면 즉시 포맷팅 또는 압축. 오류 라인 하이라이트. 원클릭 복사.',
    taglineBase64: '온라인 Base64 인코더 및 디코더. 유니코드 문자 지원.',
    taglineUrl: 'URL 인코딩 및 디코딩. 표준 encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Unix 타임스탬프와 날짜 간 변환. 초/밀리초 자동 감지.',
    taglineMarkdown: '분할 창 미리보기로 실시간 Markdown 편집. GitHub Flavored Markdown.',
    taglineDomain: '모든 도메인의 WHOIS 정보 조회. 등록 가능 여부 확인.',
    footerImageTools: '이미지 도구',
    footerDevTools: '개발 도구',
    footerAbout: '소개',
    footerAboutText: '개발자와 디자이너를 위한 무료 온라인 도구 모음. 모든 도구는 브라우저에서 로컬로 실행되며 데이터는 절대 업로드되지 않습니다.',
    footerBottom: '© 2026 DevKit HQ · 로컬 처리 · 개인정보 보호 우선',
    footerMadeWith: 'Made with',
    backHome: '← 홈으로 돌아가기',
    footer: '© 2026 DevKit HQ · 모든 도구는 브라우저에서 로컬로 실행 · 개인정보 안전',
    statTools: '도구',
    statLocal: '로컬 처리',
    statPrivacy: '데이터 업로드 없음',
    themeDark: '다크 모드',
    themeLight: '라이트 모드',
    copied: '클립보드에 복사됨',
    error: '오류가 발생했습니다. 다시 시도해 주세요.',
    processing: '처리 중...',
    done: '완료',
    pageTitle: 'DevKit HQ — 무료 온라인 이미지 및 코드 도구',
    pageTitleCompress: '이미지 압축 — DevKit HQ',
    pageTitleConvert: '형식 변환 — DevKit HQ',
    pageTitleResize: '자르기 및 크기 조정 — DevKit HQ',
    pageTitleWatermark: '워터마크 — DevKit HQ',
    pageTitleImgBase64: '이미지→Base64 — DevKit HQ',
    pageTitlePalette: '색상 팔레트 — DevKit HQ',
    pageTitleJson: 'JSON 포맷터 — DevKit HQ',
    pageTitleBase64: 'Base64 코덱 — DevKit HQ',
    pageTitleUrl: 'URL 코덱 — DevKit HQ',
    pageTitleTimestamp: '타임스탬프 변환 — DevKit HQ',
    pageTitleMarkdown: 'Markdown 미리보기 — DevKit HQ',
    pageTitleDomain: '도메인 조회 — DevKit HQ',
  },
  ru: {
    navHome: 'Главная',
    navImageTools: 'Инструменты для изображений',
    navDevTools: 'Инструменты разработчика',
    navDomain: 'Поиск доменов',
    heroBadge: '12 бесплатных онлайн-инструментов',
    heroTitle: 'Инструменты для изображений и кода<br><span>всё в вашем браузере</span>',
    heroSub: 'Приватность прежде всего. Всё обрабатывается локально. Онлайн-инструменты для разработчиков и дизайнеров.',
    heroCTA: 'Начать',
    heroGithub: 'GitHub',
    secImage: 'Инструменты для изображений',
    secImageSub: 'Сжатие, конвертация, водяные знаки, палитры — всё через Canvas',
    secDev: 'Инструменты разработчика',
    secDevSub: 'Форматирование, кодирование, декодирование — ежедневные инструменты',
    descCompress: 'Умное сжатие JPEG / PNG / WebP. Пакетная обработка, локально.',
    descConvert: 'Конвертация между JPEG, PNG, WebP с настройкой качества и размера.',
    descResize: 'Обрезка и изменение размера изображений с визуальным редактором.',
    descWatermark: 'Добавление текстовых или графических водяных знаков для защиты работ.',
    descImgBase64: 'Кодирование изображений в Base64. Копирование в один клик.',
    descPalette: 'Извлечение доминирующих цветов из изображения. Создание палитр.',
    descJson: 'Вставьте JSON — мгновенное форматирование с подсветкой ошибок.',
    descBase64: 'Кодирование и декодирование текста в/из Base64. Поддержка Unicode.',
    descUrl: 'Кодирование и декодирование URL. encodeURI / decodeURI.',
    descTimestamp: 'Конвертация Unix-времени в читаемые даты и обратно.',
    descMarkdown: 'Предпросмотр Markdown с разделённым экраном редактирования.',
    descDomain: 'Поиск информации WHOIS о домене. Проверка доступности.',
    toolCompress: 'Сжатие изображений',
    toolConvert: 'Конвертация форматов',
    toolResize: 'Обрезка и размер',
    toolWatermark: 'Водяной знак',
    toolImgBase64: 'Изображение в Base64',
    toolPalette: 'Цветовая палитра',
    toolJson: 'Форматирование JSON',
    toolBase64: 'Кодек Base64',
    toolUrl: 'Кодек URL',
    toolTimestamp: 'Временная метка',
    toolMarkdown: 'Предпросмотр Markdown',
    toolDomain: 'Поиск доменов',
    taglineCompress: 'Умное сжатие JPEG / PNG / WebP. Вся обработка выполняется локально в браузере.',
    taglineConvert: 'Конвертация между форматами JPEG, PNG, WebP с контролем качества и размера.',
    taglineResize: 'Визуальный инструмент обрезки с фиксацией пропорций и предустановленными размерами.',
    taglineWatermark: 'Добавление текстовых или графических водяных знаков для защиты работ.',
    taglineImgBase64: 'Кодирование изображений в текст Base64 для вставки в HTML/CSS.',
    taglinePalette: 'Загрузите изображение для автоматического извлечения доминирующих цветов и палитр.',
    taglineJson: 'Вставьте JSON для мгновенного форматирования или минификации с подсветкой строк с ошибками. Копирование в один клик.',
    taglineBase64: 'Онлайн кодировщик и декодировщик Base64. Поддержка символов Unicode.',
    taglineUrl: 'Кодирование и декодирование URL. Стандартные encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Конвертация между Unix-временем и датами. Автоопределение секунд/миллисекунд.',
    taglineMarkdown: 'Редактор Markdown с разделённым предпросмотром. GitHub Flavored Markdown.',
    taglineDomain: 'Поиск информации WHOIS о любом домене. Проверка возможности регистрации.',
    footerImageTools: 'Инструменты для изображений',
    footerDevTools: 'Инструменты разработчика',
    footerAbout: 'О проекте',
    footerAboutText: 'Бесплатные онлайн-инструменты для разработчиков и дизайнеров. Все инструменты работают локально в вашем браузере — данные никогда не загружаются.',
    footerBottom: '© 2026 DevKit HQ · Локальная обработка · Приватность прежде всего',
    footerMadeWith: 'Сделано с',
    backHome: '← На главную',
    footer: '© 2026 DevKit HQ · Все инструменты работают локально в браузере · Конфиденциальность',
    statTools: 'Инструментов',
    statLocal: 'Локальная обработка',
    statPrivacy: 'Без загрузки данных',
    themeDark: 'Тёмная тема',
    themeLight: 'Светлая тема',
    copied: 'Скопировано в буфер обмена',
    error: 'Произошла ошибка. Пожалуйста, попробуйте снова.',
    processing: 'Обработка...',
    done: 'Готово',
    pageTitle: 'DevKit HQ — Бесплатные онлайн-инструменты для изображений и кода',
    pageTitleCompress: 'Сжатие изображений — DevKit HQ',
    pageTitleConvert: 'Конвертация форматов — DevKit HQ',
    pageTitleResize: 'Обрезка и размер — DevKit HQ',
    pageTitleWatermark: 'Водяной знак — DevKit HQ',
    pageTitleImgBase64: 'Изображение в Base64 — DevKit HQ',
    pageTitlePalette: 'Цветовая палитра — DevKit HQ',
    pageTitleJson: 'Форматирование JSON — DevKit HQ',
    pageTitleBase64: 'Кодек Base64 — DevKit HQ',
    pageTitleUrl: 'Кодек URL — DevKit HQ',
    pageTitleTimestamp: 'Конвертер времени — DevKit HQ',
    pageTitleMarkdown: 'Предпросмотр Markdown — DevKit HQ',
    pageTitleDomain: 'Поиск доменов — DevKit HQ',
  },
  pt: {
    navHome: 'Início',
    navImageTools: 'Ferramentas de Imagem',
    navDevTools: 'Ferramentas Dev',
    navDomain: 'Consulta de Domínio',
    heroBadge: '12 Ferramentas Online Gratuitas',
    heroTitle: 'Ferramentas de imagem e código<br><span>tudo no seu navegador</span>',
    heroSub: 'Privacidade em primeiro lugar. Tudo é processado localmente. A caixa de ferramentas online para desenvolvedores e designers.',
    heroCTA: 'Começar',
    heroGithub: 'GitHub',
    secImage: 'Ferramentas de Imagem',
    secImageSub: 'Comprimir, converter, marca d\'água, extrair paletas — tudo via Canvas',
    secDev: 'Ferramentas Dev',
    secDevSub: 'Formatar, codificar, decodificar — essenciais do dia a dia',
    descCompress: 'Compressão inteligente para JPEG / PNG / WebP. Processamento em lote, local.',
    descConvert: 'Converter entre JPEG, PNG, WebP com controles de qualidade e tamanho.',
    descResize: 'Cortar e redimensionar imagens com um editor visual interativo.',
    descWatermark: 'Adicionar marcas d\'água de texto ou imagem para proteger seu trabalho.',
    descImgBase64: 'Codificar imagens em texto Base64. Cópia com um clique.',
    descPalette: 'Extrair cores dominantes de qualquer imagem. Gerar paletas.',
    descJson: 'Cole JSON bagunçado e obtenha formatação instantânea com destaque de erros.',
    descBase64: 'Codificar e decodificar texto de/para Base64. Suporta Unicode.',
    descUrl: 'Codificar e decodificar URL. encodeURI / decodeURI.',
    descTimestamp: 'Converter entre timestamps Unix e datas legíveis.',
    descMarkdown: 'Pré-visualização ao vivo de Markdown com edição em painel dividido.',
    descDomain: 'Consultar informações WHOIS de qualquer domínio. Verificar disponibilidade.',
    toolCompress: 'Compressão de Imagem',
    toolConvert: 'Conversão de Formato',
    toolResize: 'Cortar e Redimensionar',
    toolWatermark: 'Marca D\'água',
    toolImgBase64: 'Imagem para Base64',
    toolPalette: 'Paleta de Cores',
    toolJson: 'Formatador JSON',
    toolBase64: 'Codec Base64',
    toolUrl: 'Codec URL',
    toolTimestamp: 'Timestamp',
    toolMarkdown: 'Pré-visualização Markdown',
    toolDomain: 'Consulta de Domínio',
    taglineCompress: 'Compressão inteligente de JPEG / PNG / WebP. Todo o processamento é feito localmente no navegador.',
    taglineConvert: 'Converter entre formatos JPEG, PNG, WebP com controles de qualidade e tamanho.',
    taglineResize: 'Ferramenta de corte visual com bloqueio de proporção e tamanhos predefinidos.',
    taglineWatermark: 'Adicionar marcas d\'água de texto ou imagem para proteger seu trabalho.',
    taglineImgBase64: 'Codificar imagens em texto Base64 para incorporar em HTML/CSS.',
    taglinePalette: 'Envie uma imagem para extrair automaticamente cores dominantes e paletas.',
    taglineJson: 'Cole JSON para formatação ou minificação instantânea com destaque de linhas de erro. Cópia com um clique.',
    taglineBase64: 'Codificador e decodificador Base64 online. Suporta caracteres Unicode.',
    taglineUrl: 'Codificação e decodificação de URL. Padrão encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Converter entre timestamps Unix e datas. Detecta automaticamente segundos/milissegundos.',
    taglineMarkdown: 'Editor Markdown ao vivo com pré-visualização em painel dividido. GitHub Flavored Markdown.',
    taglineDomain: 'Consultar informações WHOIS de qualquer domínio. Verificar disponibilidade de registro.',
    footerImageTools: 'Ferramentas de Imagem',
    footerDevTools: 'Ferramentas Dev',
    footerAbout: 'Sobre',
    footerAboutText: 'Uma caixa de ferramentas online gratuita para desenvolvedores e designers. Todas as ferramentas são executadas localmente no navegador — nenhum dado é enviado.',
    footerBottom: '© 2026 DevKit HQ · Processamento local · Privacidade primeiro',
    footerMadeWith: 'Feito com',
    backHome: '← Voltar ao Início',
    footer: '© 2026 DevKit HQ · Todas as ferramentas rodam localmente no navegador · Privacidade segura',
    statTools: 'Ferramentas',
    statLocal: 'Processamento Local',
    statPrivacy: 'Sem Upload de Dados',
    themeDark: 'Modo escuro',
    themeLight: 'Modo claro',
    copied: 'Copiado para a área de transferência',
    error: 'Algo deu errado. Por favor, tente novamente.',
    processing: 'Processando...',
    done: 'Concluído',
    pageTitle: 'DevKit HQ — Ferramentas Online Gratuitas para Imagens e Código',
    pageTitleCompress: 'Compressão de Imagem — DevKit HQ',
    pageTitleConvert: 'Conversão de Formato — DevKit HQ',
    pageTitleResize: 'Cortar e Redimensionar — DevKit HQ',
    pageTitleWatermark: 'Marca D\'água — DevKit HQ',
    pageTitleImgBase64: 'Imagem para Base64 — DevKit HQ',
    pageTitlePalette: 'Paleta de Cores — DevKit HQ',
    pageTitleJson: 'Formatador JSON — DevKit HQ',
    pageTitleBase64: 'Codec Base64 — DevKit HQ',
    pageTitleUrl: 'Codec URL — DevKit HQ',
    pageTitleTimestamp: 'Conversor de Timestamp — DevKit HQ',
    pageTitleMarkdown: 'Pré-visualização Markdown — DevKit HQ',
    pageTitleDomain: 'Consulta de Domínio — DevKit HQ',
  },
  es: {
    navHome: 'Inicio',
    navImageTools: 'Herramientas de Imagen',
    navDevTools: 'Herramientas Dev',
    navDomain: 'Búsqueda de Dominio',
    heroBadge: '12 Herramientas Online Gratuitas',
    heroTitle: 'Herramientas de imagen y código<br><span>todo en tu navegador</span>',
    heroSub: 'Privacidad primero. Todo se procesa localmente. La caja de herramientas online para desarrolladores y diseñadores.',
    heroCTA: 'Comenzar',
    heroGithub: 'GitHub',
    secImage: 'Herramientas de Imagen',
    secImageSub: 'Comprimir, convertir, marcas de agua, extraer paletas — todo mediante Canvas',
    secDev: 'Herramientas Dev',
    secDevSub: 'Formatear, codificar, decodificar — esenciales diarios para desarrolladores',
    descCompress: 'Compresión inteligente para JPEG / PNG / WebP. Procesamiento por lotes, local.',
    descConvert: 'Convertir entre JPEG, PNG, WebP con controles de calidad y tamaño.',
    descResize: 'Recortar y redimensionar imágenes con un editor visual interactivo.',
    descWatermark: 'Añadir marcas de agua de texto o imagen para proteger tu trabajo.',
    descImgBase64: 'Codificar imágenes a texto Base64. Copia con un clic.',
    descPalette: 'Extraer colores dominantes de cualquier imagen. Generar paletas.',
    descJson: 'Pega JSON desordenado y obtén formateo instantáneo con resaltado de errores.',
    descBase64: 'Codificar y decodificar texto de/a Base64. Compatible con Unicode.',
    descUrl: 'Codificar y decodificar URL. encodeURI / decodeURI.',
    descTimestamp: 'Convertir entre timestamps Unix y fechas legibles.',
    descMarkdown: 'Vista previa en vivo de Markdown con edición en panel dividido.',
    descDomain: 'Consultar información WHOIS de cualquier dominio. Verificar disponibilidad.',
    toolCompress: 'Compresión de Imagen',
    toolConvert: 'Conversión de Formato',
    toolResize: 'Recortar y Redimensionar',
    toolWatermark: 'Marca de Agua',
    toolImgBase64: 'Imagen a Base64',
    toolPalette: 'Paleta de Colores',
    toolJson: 'Formateador JSON',
    toolBase64: 'Codec Base64',
    toolUrl: 'Codec URL',
    toolTimestamp: 'Timestamp',
    toolMarkdown: 'Vista Previa Markdown',
    toolDomain: 'Búsqueda de Dominio',
    taglineCompress: 'Compresión inteligente JPEG / PNG / WebP. Todo el procesamiento se realiza localmente en tu navegador.',
    taglineConvert: 'Convertir entre formatos JPEG, PNG, WebP con controles de calidad y tamaño.',
    taglineResize: 'Herramienta de recorte visual con bloqueo de relación de aspecto y tamaños predefinidos.',
    taglineWatermark: 'Añadir marcas de agua de texto o imagen para proteger tu trabajo.',
    taglineImgBase64: 'Codificar imágenes a texto Base64 para incrustar en HTML/CSS.',
    taglinePalette: 'Sube una imagen para extraer automáticamente colores dominantes y paletas.',
    taglineJson: 'Pega JSON para formateo o minificación instantánea con resaltado de líneas de error. Copia con un clic.',
    taglineBase64: 'Codificador y decodificador Base64 online. Compatible con caracteres Unicode.',
    taglineUrl: 'Codificación y decodificación de URL. Estándar encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Convertir entre timestamps Unix y fechas. Detección automática de segundos/milisegundos.',
    taglineMarkdown: 'Editor Markdown en vivo con vista previa en panel dividido. GitHub Flavored Markdown.',
    taglineDomain: 'Consultar información WHOIS de cualquier dominio. Verificar disponibilidad de registro.',
    footerImageTools: 'Herramientas de Imagen',
    footerDevTools: 'Herramientas Dev',
    footerAbout: 'Acerca de',
    footerAboutText: 'Una caja de herramientas online gratuita para desarrolladores y diseñadores. Todas las herramientas se ejecutan localmente en tu navegador — nunca se suben datos.',
    footerBottom: '© 2026 DevKit HQ · Procesamiento local · Privacidad primero',
    footerMadeWith: 'Hecho con',
    backHome: '← Volver al Inicio',
    footer: '© 2026 DevKit HQ · Todas las herramientas se ejecutan localmente en el navegador · Privacidad segura',
    statTools: 'Herramientas',
    statLocal: 'Procesamiento Local',
    statPrivacy: 'Sin Carga de Datos',
    themeDark: 'Modo oscuro',
    themeLight: 'Modo claro',
    copied: 'Copiado al portapapeles',
    error: 'Algo salió mal. Por favor, inténtalo de nuevo.',
    processing: 'Procesando...',
    done: 'Hecho',
    pageTitle: 'DevKit HQ — Herramientas Online Gratuitas para Imágenes y Código',
    pageTitleCompress: 'Compresión de Imagen — DevKit HQ',
    pageTitleConvert: 'Conversión de Formato — DevKit HQ',
    pageTitleResize: 'Recortar y Redimensionar — DevKit HQ',
    pageTitleWatermark: 'Marca de Agua — DevKit HQ',
    pageTitleImgBase64: 'Imagen a Base64 — DevKit HQ',
    pageTitlePalette: 'Paleta de Colores — DevKit HQ',
    pageTitleJson: 'Formateador JSON — DevKit HQ',
    pageTitleBase64: 'Codec Base64 — DevKit HQ',
    pageTitleUrl: 'Codec URL — DevKit HQ',
    pageTitleTimestamp: 'Conversor de Timestamp — DevKit HQ',
    pageTitleMarkdown: 'Vista Previa Markdown — DevKit HQ',
    pageTitleDomain: 'Búsqueda de Dominio — DevKit HQ',
  },
  fr: {
    navHome: 'Accueil',
    navImageTools: 'Outils Image',
    navDevTools: 'Outils Dev',
    navDomain: 'Recherche de Domaine',
    heroBadge: '12 Outils en Ligne Gratuits',
    heroTitle: 'Outils pour images et code<br><span>tout dans votre navigateur</span>',
    heroSub: 'Confidentialité d\'abord. Tout est traité localement. La boîte à outils en ligne pour les développeurs et designers.',
    heroCTA: 'Commencer',
    heroGithub: 'GitHub',
    secImage: 'Outils Image',
    secImageSub: 'Compresser, convertir, filigrane, extraire des palettes — tout via Canvas',
    secDev: 'Outils Dev',
    secDevSub: 'Formatter, encoder, décoder — essentiels quotidiens pour les développeurs',
    descCompress: 'Compression intelligente pour JPEG / PNG / WebP. Traitement par lot, local.',
    descConvert: 'Convertir entre JPEG, PNG, WebP avec contrôles de qualité et de taille.',
    descResize: 'Recadrer et redimensionner des images avec un éditeur visuel interactif.',
    descWatermark: 'Ajouter des filigranes de texte ou d\'image pour protéger votre travail.',
    descImgBase64: 'Encoder des images en texte Base64. Copie en un clic.',
    descPalette: 'Extraire les couleurs dominantes de n\'importe quelle image. Générer des palettes.',
    descJson: 'Collez du JSON désordonné et obtenez un formatage instantané avec surlignage des erreurs.',
    descBase64: 'Encoder et décoder du texte vers/depuis Base64. Prend en charge Unicode.',
    descUrl: 'Encoder et décoder des URL. encodeURI / decodeURI.',
    descTimestamp: 'Convertir entre les timestamps Unix et les dates lisibles.',
    descMarkdown: 'Aperçu en direct de Markdown avec édition en panneau divisé.',
    descDomain: 'Rechercher des informations WHOIS sur un domaine. Vérifier la disponibilité.',
    toolCompress: 'Compression d\'Image',
    toolConvert: 'Conversion de Format',
    toolResize: 'Recadrer et Redimensionner',
    toolWatermark: 'Filigrane',
    toolImgBase64: 'Image en Base64',
    toolPalette: 'Palette de Couleurs',
    toolJson: 'Formateur JSON',
    toolBase64: 'Codec Base64',
    toolUrl: 'Codec URL',
    toolTimestamp: 'Horodatage',
    toolMarkdown: 'Aperçu Markdown',
    toolDomain: 'Recherche de Domaine',
    taglineCompress: 'Compression intelligente JPEG / PNG / WebP. Tout le traitement est effectué localement dans votre navigateur.',
    taglineConvert: 'Convertir entre les formats JPEG, PNG, WebP avec contrôles de qualité et de taille.',
    taglineResize: 'Outil de recadrage visuel avec verrouillage du ratio et tailles prédéfinies.',
    taglineWatermark: 'Ajouter des filigranes de texte ou d\'image pour protéger votre travail.',
    taglineImgBase64: 'Encoder des images en texte Base64 pour les intégrer dans HTML/CSS.',
    taglinePalette: 'Téléchargez une image pour extraire automatiquement les couleurs dominantes et les palettes.',
    taglineJson: 'Collez du JSON pour un formatage ou une minification instantanée avec surlignage des lignes d\'erreur. Copie en un clic.',
    taglineBase64: 'Encodeur et décodeur Base64 en ligne. Prend en charge les caractères Unicode.',
    taglineUrl: 'Encodage et décodage d\'URL. Standard encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Convertir entre les timestamps Unix et les dates. Détection automatique secondes/millisecondes.',
    taglineMarkdown: 'Éditeur Markdown en direct avec aperçu en panneau divisé. GitHub Flavored Markdown.',
    taglineDomain: 'Rechercher des informations WHOIS sur n\'importe quel domaine. Vérifier la disponibilité.',
    footerImageTools: 'Outils Image',
    footerDevTools: 'Outils Dev',
    footerAbout: 'À propos',
    footerAboutText: 'Une boîte à outils en ligne gratuite pour les développeurs et designers. Tous les outils fonctionnent localement dans votre navigateur — aucune donnée n\'est jamais téléchargée.',
    footerBottom: '© 2026 DevKit HQ · Traitement local · Confidentialité d\'abord',
    footerMadeWith: 'Fait avec',
    backHome: '← Retour à l\'Accueil',
    footer: '© 2026 DevKit HQ · Tous les outils fonctionnent localement dans le navigateur · Confidentialité',
    statTools: 'Outils',
    statLocal: 'Traitement Local',
    statPrivacy: 'Aucun Téléchargement',
    themeDark: 'Mode sombre',
    themeLight: 'Mode clair',
    copied: 'Copié dans le presse-papiers',
    error: 'Une erreur est survenue. Veuillez réessayer.',
    processing: 'Traitement...',
    done: 'Terminé',
    pageTitle: 'DevKit HQ — Outils en Ligne Gratuits pour Images et Code',
    pageTitleCompress: 'Compression d\'Image — DevKit HQ',
    pageTitleConvert: 'Conversion de Format — DevKit HQ',
    pageTitleResize: 'Recadrer et Redimensionner — DevKit HQ',
    pageTitleWatermark: 'Filigrane — DevKit HQ',
    pageTitleImgBase64: 'Image en Base64 — DevKit HQ',
    pageTitlePalette: 'Palette de Couleurs — DevKit HQ',
    pageTitleJson: 'Formateur JSON — DevKit HQ',
    pageTitleBase64: 'Codec Base64 — DevKit HQ',
    pageTitleUrl: 'Codec URL — DevKit HQ',
    pageTitleTimestamp: 'Convertisseur d\'Horodatage — DevKit HQ',
    pageTitleMarkdown: 'Aperçu Markdown — DevKit HQ',
    pageTitleDomain: 'Recherche de Domaine — DevKit HQ',
  },
  de: {
    navHome: 'Start',
    navImageTools: 'Bildwerkzeuge',
    navDevTools: 'Entwicklerwerkzeuge',
    navDomain: 'Domain-Suche',
    heroBadge: '12 Kostenlose Online-Tools',
    heroTitle: 'Bild- und Code-Tools<br><span>alles im Browser</span>',
    heroSub: 'Datenschutz zuerst. Alles wird lokal verarbeitet. Die Online-Toolbox für Entwickler und Designer.',
    heroCTA: 'Loslegen',
    heroGithub: 'GitHub',
    secImage: 'Bildwerkzeuge',
    secImageSub: 'Komprimieren, konvertieren, Wasserzeichen, Paletten extrahieren — alles über Canvas',
    secDev: 'Entwicklerwerkzeuge',
    secDevSub: 'Formatieren, codieren, decodieren — tägliche Begleiter für Entwickler',
    descCompress: 'Intelligente Komprimierung für JPEG / PNG / WebP. Stapelverarbeitung, lokal.',
    descConvert: 'Konvertieren zwischen JPEG, PNG, WebP mit Qualitäts- und Größeneinstellungen.',
    descResize: 'Bilder zuschneiden und skalieren mit einem interaktiven visuellen Editor.',
    descWatermark: 'Text- oder Bildwasserzeichen zum Schutz Ihrer Arbeit hinzufügen.',
    descImgBase64: 'Bilder in Base64-Text codieren. Kopieren mit einem Klick.',
    descPalette: 'Dominante Farben aus jedem Bild extrahieren. Paletten generieren.',
    descJson: 'JSON einfügen und sofortige Formatierung mit Fehlerhervorhebung erhalten.',
    descBase64: 'Text von/nach Base64 codieren und decodieren. Unterstützt Unicode.',
    descUrl: 'URL codieren und decodieren. encodeURI / decodeURI.',
    descTimestamp: 'Konvertieren zwischen Unix-Timestamps und lesbaren Daten.',
    descMarkdown: 'Live-Markdown-Vorschau mit geteiltem Bearbeitungsbereich.',
    descDomain: 'WHOIS-Informationen für jede Domain abrufen. Verfügbarkeit prüfen.',
    toolCompress: 'Bildkomprimierung',
    toolConvert: 'Formatkonvertierung',
    toolResize: 'Zuschneiden & Skalieren',
    toolWatermark: 'Wasserzeichen',
    toolImgBase64: 'Bild zu Base64',
    toolPalette: 'Farbpalette',
    toolJson: 'JSON-Formatierer',
    toolBase64: 'Base64-Codec',
    toolUrl: 'URL-Codec',
    toolTimestamp: 'Zeitstempel',
    toolMarkdown: 'Markdown-Vorschau',
    toolDomain: 'Domain-Suche',
    taglineCompress: 'Intelligente JPEG / PNG / WebP-Komprimierung. Die gesamte Verarbeitung erfolgt lokal in Ihrem Browser.',
    taglineConvert: 'Konvertieren zwischen JPEG-, PNG-, WebP-Formaten mit Qualitäts- und Größeneinstellungen.',
    taglineResize: 'Visuelles Zuschneidewerkzeug mit Seitenverhältnissperre und voreingestellten Größen.',
    taglineWatermark: 'Text- oder Bildwasserzeichen zum Schutz Ihrer Arbeit hinzufügen.',
    taglineImgBase64: 'Bilder in Base64-Text codieren zum Einbetten in HTML/CSS.',
    taglinePalette: 'Laden Sie ein Bild hoch, um automatisch dominante Farben und Paletten zu extrahieren.',
    taglineJson: 'JSON einfügen für sofortige Formatierung oder Minifizierung mit Fehlerzeilen-Hervorhebung. Kopieren mit einem Klick.',
    taglineBase64: 'Online Base64-Encoder und -Decoder. Unterstützt Unicode-Zeichen.',
    taglineUrl: 'URL-Codierung und -Decodierung. Standard encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Konvertieren zwischen Unix-Timestamps und Daten. Automatische Erkennung von Sekunden/Millisekunden.',
    taglineMarkdown: 'Live-Markdown-Editor mit geteilter Vorschau. GitHub Flavored Markdown.',
    taglineDomain: 'WHOIS-Informationen für jede Domain abrufen. Verfügbarkeit der Registrierung prüfen.',
    footerImageTools: 'Bildwerkzeuge',
    footerDevTools: 'Entwicklerwerkzeuge',
    footerAbout: 'Über',
    footerAboutText: 'Eine kostenlose Online-Toolbox für Entwickler und Designer. Alle Tools laufen lokal in Ihrem Browser — es werden niemals Daten hochgeladen.',
    footerBottom: '© 2026 DevKit HQ · Lokale Verarbeitung · Datenschutz zuerst',
    footerMadeWith: 'Gemacht mit',
    backHome: '← Zurück zur Startseite',
    footer: '© 2026 DevKit HQ · Alle Tools laufen lokal im Browser · Datenschutz',
    statTools: 'Werkzeuge',
    statLocal: 'Lokale Verarbeitung',
    statPrivacy: 'Kein Daten-Upload',
    themeDark: 'Dunkelmodus',
    themeLight: 'Hellmodus',
    copied: 'In die Zwischenablage kopiert',
    error: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    processing: 'Verarbeitung...',
    done: 'Fertig',
    pageTitle: 'DevKit HQ — Kostenlose Online-Tools für Bilder und Code',
    pageTitleCompress: 'Bildkomprimierung — DevKit HQ',
    pageTitleConvert: 'Formatkonvertierung — DevKit HQ',
    pageTitleResize: 'Zuschneiden & Skalieren — DevKit HQ',
    pageTitleWatermark: 'Wasserzeichen — DevKit HQ',
    pageTitleImgBase64: 'Bild zu Base64 — DevKit HQ',
    pageTitlePalette: 'Farbpalette — DevKit HQ',
    pageTitleJson: 'JSON-Formatierer — DevKit HQ',
    pageTitleBase64: 'Base64-Codec — DevKit HQ',
    pageTitleUrl: 'URL-Codec — DevKit HQ',
    pageTitleTimestamp: 'Zeitstempel-Konverter — DevKit HQ',
    pageTitleMarkdown: 'Markdown-Vorschau — DevKit HQ',
    pageTitleDomain: 'Domain-Suche — DevKit HQ',
  },
  it: {
    navHome: 'Home',
    navImageTools: 'Strumenti Immagine',
    navDevTools: 'Strumenti Sviluppo',
    navDomain: 'Ricerca Dominio',
    heroBadge: '12 Strumenti Online Gratuiti',
    heroTitle: 'Strumenti per immagini e codice<br><span>tutto nel tuo browser</span>',
    heroSub: 'Privacy al primo posto. Tutto viene elaborato localmente. La cassetta degli attrezzi online per sviluppatori e designer.',
    heroCTA: 'Inizia',
    heroGithub: 'GitHub',
    secImage: 'Strumenti Immagine',
    secImageSub: 'Comprimi, converti, filigrana, estrai palette — tutto tramite Canvas',
    secDev: 'Strumenti Sviluppo',
    secDevSub: 'Formatta, codifica, decodifica — essenziali quotidiani per sviluppatori',
    descCompress: 'Compressione intelligente per JPEG / PNG / WebP. Elaborazione batch, locale.',
    descConvert: 'Converti tra JPEG, PNG, WebP con controlli di qualità e dimensioni.',
    descResize: 'Ritaglia e ridimensiona immagini con un editor visivo interattivo.',
    descWatermark: 'Aggiungi filigrane di testo o immagine per proteggere il tuo lavoro.',
    descImgBase64: 'Codifica immagini in testo Base64. Copia con un clic.',
    descPalette: 'Estrai i colori dominanti da qualsiasi immagine. Genera palette.',
    descJson: 'Incolla JSON disordinato e ottieni formattazione istantanea con evidenziazione degli errori.',
    descBase64: 'Codifica e decodifica testo da/verso Base64. Supporta Unicode.',
    descUrl: 'Codifica e decodifica URL. encodeURI / decodeURI.',
    descTimestamp: 'Converti tra timestamp Unix e date leggibili.',
    descMarkdown: 'Anteprima dal vivo di Markdown con modifica a pannello diviso.',
    descDomain: 'Cerca informazioni WHOIS per qualsiasi dominio. Verifica disponibilità.',
    toolCompress: 'Compressione Immagine',
    toolConvert: 'Conversione Formato',
    toolResize: 'Ritaglia e Ridimensiona',
    toolWatermark: 'Filigrana',
    toolImgBase64: 'Immagine in Base64',
    toolPalette: 'Tavolozza Colori',
    toolJson: 'Formattatore JSON',
    toolBase64: 'Codec Base64',
    toolUrl: 'Codec URL',
    toolTimestamp: 'Timestamp',
    toolMarkdown: 'Anteprima Markdown',
    toolDomain: 'Ricerca Dominio',
    taglineCompress: 'Compressione intelligente JPEG / PNG / WebP. Tutta l\'elaborazione avviene localmente nel browser.',
    taglineConvert: 'Converti tra i formati JPEG, PNG, WebP con controlli di qualità e dimensioni.',
    taglineResize: 'Strumento di ritaglio visivo con blocco delle proporzioni e dimensioni predefinite.',
    taglineWatermark: 'Aggiungi filigrane di testo o immagine per proteggere il tuo lavoro.',
    taglineImgBase64: 'Codifica immagini in testo Base64 per incorporarle in HTML/CSS.',
    taglinePalette: 'Carica un\'immagine per estrarre automaticamente colori dominanti e palette.',
    taglineJson: 'Incolla JSON per formattazione o minificazione istantanea con evidenziazione delle righe di errore. Copia con un clic.',
    taglineBase64: 'Codificatore e decodificatore Base64 online. Supporta caratteri Unicode.',
    taglineUrl: 'Codifica e decodifica URL. Standard encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Converti tra timestamp Unix e date. Rilevamento automatico secondi/millisecondi.',
    taglineMarkdown: 'Editor Markdown dal vivo con anteprima a pannello diviso. GitHub Flavored Markdown.',
    taglineDomain: 'Cerca informazioni WHOIS per qualsiasi dominio. Verifica disponibilità di registrazione.',
    footerImageTools: 'Strumenti Immagine',
    footerDevTools: 'Strumenti Sviluppo',
    footerAbout: 'Informazioni',
    footerAboutText: 'Una cassetta degli attrezzi online gratuita per sviluppatori e designer. Tutti gli strumenti funzionano localmente nel browser — nessun dato viene mai caricato.',
    footerBottom: '© 2026 DevKit HQ · Elaborazione locale · Privacy al primo posto',
    footerMadeWith: 'Fatto con',
    backHome: '← Torna alla Home',
    footer: '© 2026 DevKit HQ · Tutti gli strumenti funzionano localmente nel browser · Privacy sicura',
    statTools: 'Strumenti',
    statLocal: 'Elaborazione Locale',
    statPrivacy: 'Nessun Upload Dati',
    themeDark: 'Modalità scura',
    themeLight: 'Modalità chiara',
    copied: 'Copiato negli appunti',
    error: 'Qualcosa è andato storto. Per favore riprova.',
    processing: 'Elaborazione...',
    done: 'Fatto',
    pageTitle: 'DevKit HQ — Strumenti Online Gratuiti per Immagini e Codice',
    pageTitleCompress: 'Compressione Immagine — DevKit HQ',
    pageTitleConvert: 'Conversione Formato — DevKit HQ',
    pageTitleResize: 'Ritaglia e Ridimensiona — DevKit HQ',
    pageTitleWatermark: 'Filigrana — DevKit HQ',
    pageTitleImgBase64: 'Immagine in Base64 — DevKit HQ',
    pageTitlePalette: 'Tavolozza Colori — DevKit HQ',
    pageTitleJson: 'Formattatore JSON — DevKit HQ',
    pageTitleBase64: 'Codec Base64 — DevKit HQ',
    pageTitleUrl: 'Codec URL — DevKit HQ',
    pageTitleTimestamp: 'Convertitore Timestamp — DevKit HQ',
    pageTitleMarkdown: 'Anteprima Markdown — DevKit HQ',
    pageTitleDomain: 'Ricerca Dominio — DevKit HQ',
  },
  ar: {
    navHome: 'الرئيسية',
    navImageTools: 'أدوات الصور',
    navDevTools: 'أدوات المطور',
    navDomain: 'بحث النطاق',
    heroBadge: '12 أداة مجانية عبر الإنترنت',
    heroTitle: 'أدوات الصور والكود<br><span>كل شيء في متصفحك</span>',
    heroSub: 'الخصوصية أولاً. كل شيء يعالج محلياً. صندوق الأدوات الإلكتروني للمطورين والمصممين.',
    heroCTA: 'ابدأ الآن',
    heroGithub: 'GitHub',
    secImage: 'أدوات الصور',
    secImageSub: 'ضغط، تحويل، علامة مائية، استخراج الألوان — كل شيء عبر Canvas',
    secDev: 'أدوات المطور',
    secDevSub: 'تنسيق، ترميز، فك ترميز — أدوات يومية أساسية للمطورين',
    descCompress: 'ضغط ذكي لـ JPEG / PNG / WebP. معالجة بالمجمعة، محلياً.',
    descConvert: 'تحويل بين JPEG، PNG، WebP مع إعدادات الجودة والحجم.',
    descResize: 'قص وتغيير حجم الصور باستخدام محرر مرئي تفاعلي.',
    descWatermark: 'إضافة علامات مائية نصية أو صورية لحماية عملك.',
    descImgBase64: 'ترميز الصور إلى نص Base64. نسخ بنقرة واحدة.',
    descPalette: 'استخراج الألوان السائدة من أي صورة. إنشاء لوحات ألوان.',
    descJson: 'الصق JSON غير المرتب واحصل على تنسيق فوري مع تمييز الأخطاء.',
    descBase64: 'ترميز وفك ترميز النص من/إلى Base64. يدعم Unicode.',
    descUrl: 'ترميز وفك ترميز URL. encodeURI / decodeURI.',
    descTimestamp: 'تحويل بين طوابع الوقت Unix والتواريخ المقروءة.',
    descMarkdown: 'معاينة حية لـ Markdown مع تحرير بلوحة مقسمة.',
    descDomain: 'البحث عن معلومات WHOIS لأي نطاق. التحقق من التوفر.',
    toolCompress: 'ضغط الصور',
    toolConvert: 'تحويل الصيغ',
    toolResize: 'قص وتغيير الحجم',
    toolWatermark: 'علامة مائية',
    toolImgBase64: 'صورة إلى Base64',
    toolPalette: 'لوحة الألوان',
    toolJson: 'منسق JSON',
    toolBase64: 'مرمز Base64',
    toolUrl: 'مرمز URL',
    toolTimestamp: 'الطابع الزمني',
    toolMarkdown: 'معاينة Markdown',
    toolDomain: 'بحث النطاق',
    taglineCompress: 'ضغط ذكي لـ JPEG / PNG / WebP. جميع العمليات تتم محلياً في متصفحك.',
    taglineConvert: 'تحويل بين صيغ JPEG، PNG، WebP مع إعدادات الجودة والحجم.',
    taglineResize: 'أداة قص مرئية مع قفل نسبة العرض إلى الارتفاع وأحجام محددة مسبقاً.',
    taglineWatermark: 'إضافة علامات مائية نصية أو صورية لحماية عملك.',
    taglineImgBase64: 'ترميز الصور إلى نص Base64 لتضمينها في HTML/CSS.',
    taglinePalette: 'قم بتحميل صورة لاستخراج الألوان السائدة ولوحات الألوان تلقائياً.',
    taglineJson: 'الصق JSON للتنسيق الفوري أو التصغير مع تمييز أسطر الأخطاء. نسخ بنقرة واحدة.',
    taglineBase64: 'مشفر وفاك تشفير Base64 عبر الإنترنت. يدعم أحرف Unicode.',
    taglineUrl: 'ترميز وفك ترميز URL. قياسي encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'تحويل بين طوابع الوقت Unix والتواريخ. كشف تلقائي للثواني/الميلي ثانية.',
    taglineMarkdown: 'محرر Markdown حي مع معاينة بلوحة مقسمة. GitHub Flavored Markdown.',
    taglineDomain: 'البحث عن معلومات WHOIS لأي نطاق. التحقق من إمكانية التسجيل.',
    footerImageTools: 'أدوات الصور',
    footerDevTools: 'أدوات المطور',
    footerAbout: 'حول',
    footerAboutText: 'صندوق أدوات مجاني عبر الإنترنت للمطورين والمصممين. جميع الأدوات تعمل محلياً في متصفحك — لا يتم تحميل أي بيانات أبداً.',
    footerBottom: '© 2026 DevKit HQ · معالجة محلية · الخصوصية أولاً',
    footerMadeWith: 'صنع بـ',
    backHome: '← العودة للرئيسية',
    footer: '© 2026 DevKit HQ · جميع الأدوات تعمل محلياً في المتصفح · خصوصية آمنة',
    statTools: 'أداة',
    statLocal: 'معالجة محلية',
    statPrivacy: 'لا رفع للبيانات',
    themeDark: 'الوضع الداكن',
    themeLight: 'الوضع الفاتح',
    copied: 'تم النسخ إلى الحافظة',
    error: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    processing: 'جاري المعالجة...',
    done: 'تم',
    pageTitle: 'DevKit HQ — أدوات مجانية للصور والكود عبر الإنترنت',
    pageTitleCompress: 'ضغط الصور — DevKit HQ',
    pageTitleConvert: 'تحويل الصيغ — DevKit HQ',
    pageTitleResize: 'قص وتغيير الحجم — DevKit HQ',
    pageTitleWatermark: 'علامة مائية — DevKit HQ',
    pageTitleImgBase64: 'صورة إلى Base64 — DevKit HQ',
    pageTitlePalette: 'لوحة الألوان — DevKit HQ',
    pageTitleJson: 'منسق JSON — DevKit HQ',
    pageTitleBase64: 'مرمز Base64 — DevKit HQ',
    pageTitleUrl: 'مرمز URL — DevKit HQ',
    pageTitleTimestamp: 'محول الطابع الزمني — DevKit HQ',
    pageTitleMarkdown: 'معاينة Markdown — DevKit HQ',
    pageTitleDomain: 'بحث النطاق — DevKit HQ',
  },
  hi: {
    navHome: 'होम',
    navImageTools: 'इमेज टूल्स',
    navDevTools: 'डेव टूल्स',
    navDomain: 'डोमेन खोज',
    heroBadge: '12 मुफ्त ऑनलाइन टूल्स',
    heroTitle: 'इमेज और कोड टूल्स<br><span>सब आपके ब्राउज़र में</span>',
    heroSub: 'गोपनीयता पहले। सब कुछ स्थानीय रूप से संसाधित होता है। डेवलपर्स और डिज़ाइनर्स के लिए ऑनलाइन टूलबॉक्स।',
    heroCTA: 'शुरू करें',
    heroGithub: 'GitHub',
    secImage: 'इमेज टूल्स',
    secImageSub: 'कंप्रेस, कन्वर्ट, वॉटरमार्क, पैलेट निकालें — सब Canvas के माध्यम से',
    secDev: 'डेव टूल्स',
    secDevSub: 'फॉर्मेट, एनकोड, डीकोड — डेवलपर्स के लिए रोज़मर्रा के आवश्यक टूल्स',
    descCompress: 'JPEG / PNG / WebP के लिए स्मार्ट कंप्रेशन। बैच प्रोसेसिंग, स्थानीय।',
    descConvert: 'JPEG, PNG, WebP के बीच कन्वर्ट करें। गुणवत्ता और आकार नियंत्रण के साथ।',
    descResize: 'इंटरैक्टिव विज़ुअल एडिटर के साथ इमेज क्रॉप और रीसाइज़ करें।',
    descWatermark: 'अपने काम की सुरक्षा के लिए टेक्स्ट या इमेज वॉटरमार्क जोड़ें।',
    descImgBase64: 'इमेज को Base64 टेक्स्ट में एनकोड करें। एक क्लिक में कॉपी करें।',
    descPalette: 'किसी भी इमेज से प्रमुख रंग निकालें। पैलेट जनरेट करें।',
    descJson: 'अव्यवस्थित JSON पेस्ट करें और तुरंत फॉर्मेटिंग पाएं। एरर हाइलाइटिंग के साथ।',
    descBase64: 'टेक्स्ट को Base64 में/से एनकोड और डीकोड करें। यूनिकोड सपोर्ट।',
    descUrl: 'URL एनकोड और डीकोड करें। encodeURI / decodeURI।',
    descTimestamp: 'Unix टाइमस्टैम्प और पठनीय तिथियों के बीच कन्वर्ट करें।',
    descMarkdown: 'स्प्लिट-पेन एडिटिंग के साथ लाइव Markdown प्रीव्यू।',
    descDomain: 'किसी भी डोमेन की WHOIS जानकारी खोजें। उपलब्धता जांचें।',
    toolCompress: 'इमेज कंप्रेशन',
    toolConvert: 'फॉर्मेट कन्वर्ज़न',
    toolResize: 'क्रॉप और रीसाइज़',
    toolWatermark: 'वॉटरमार्क',
    toolImgBase64: 'इमेज से Base64',
    toolPalette: 'कलर पैलेट',
    toolJson: 'JSON फॉर्मेटर',
    toolBase64: 'Base64 कोडेक',
    toolUrl: 'URL कोडेक',
    toolTimestamp: 'टाइमस्टैम्प',
    toolMarkdown: 'Markdown प्रीव्यू',
    toolDomain: 'डोमेन खोज',
    taglineCompress: 'स्मार्ट JPEG / PNG / WebP कंप्रेशन। सभी प्रोसेसिंग आपके ब्राउज़र में स्थानीय रूप से होती है।',
    taglineConvert: 'JPEG, PNG, WebP फॉर्मेट के बीच कन्वर्ट करें। गुणवत्ता और आकार नियंत्रण के साथ।',
    taglineResize: 'आस्पेक्ट रेशियो लॉक और प्रीसेट साइज़ के साथ विज़ुअल क्रॉप टूल।',
    taglineWatermark: 'अपने काम की सुरक्षा के लिए टेक्स्ट या इमेज वॉटरमार्क जोड़ें।',
    taglineImgBase64: 'HTML/CSS में एम्बेड करने के लिए इमेज को Base64 टेक्स्ट में एनकोड करें।',
    taglinePalette: 'प्रमुख रंग और पैलेट स्वचालित रूप से निकालने के लिए इमेज अपलोड करें।',
    taglineJson: 'JSON पेस्ट करें तुरंत फॉर्मेटिंग या मिनिफिकेशन के लिए। एरर लाइन हाइलाइटिंग। एक क्लिक कॉपी।',
    taglineBase64: 'ऑनलाइन Base64 एनकोडर और डिकोडर। यूनिकोड कैरेक्टर सपोर्ट।',
    taglineUrl: 'URL एनकोडिंग और डिकोडिंग। स्टैंडर्ड encodeURIComponent / decodeURIComponent।',
    taglineTimestamp: 'Unix टाइमस्टैम्प और तिथियों के बीच कन्वर्ट करें। सेकंड/मिलीसेकंड ऑटो-डिटेक्ट।',
    taglineMarkdown: 'स्प्लिट-पेन प्रीव्यू के साथ लाइव Markdown एडिटर। GitHub Flavored Markdown।',
    taglineDomain: 'किसी भी डोमेन की WHOIS जानकारी खोजें। रजिस्ट्रेशन उपलब्धता जांचें।',
    footerImageTools: 'इमेज टूल्स',
    footerDevTools: 'डेव टूल्स',
    footerAbout: 'हमारे बारे में',
    footerAboutText: 'डेवलपर्स और डिज़ाइनर्स के लिए एक मुफ्त ऑनलाइन टूलबॉक्स। सभी टूल्स आपके ब्राउज़र में स्थानीय रूप से चलते हैं — कोई डेटा कभी अपलोड नहीं किया जाता।',
    footerBottom: '© 2026 DevKit HQ · स्थानीय प्रसंस्करण · गोपनीयता पहले',
    footerMadeWith: 'के साथ बनाया गया',
    backHome: '← होम पर वापस जाएं',
    footer: '© 2026 DevKit HQ · सभी टूल्स ब्राउज़र में स्थानीय रूप से चलते हैं · गोपनीयता सुरक्षित',
    statTools: 'टूल्स',
    statLocal: 'स्थानीय प्रसंस्करण',
    statPrivacy: 'कोई डेटा अपलोड नहीं',
    themeDark: 'डार्क मोड',
    themeLight: 'लाइट मोड',
    copied: 'क्लिपबोर्ड पर कॉपी किया गया',
    error: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
    processing: 'प्रसंस्करण...',
    done: 'पूर्ण',
    pageTitle: 'DevKit HQ — इमेज और कोड के लिए मुफ्त ऑनलाइन टूल्स',
    pageTitleCompress: 'इमेज कंप्रेशन — DevKit HQ',
    pageTitleConvert: 'फॉर्मेट कन्वर्ज़न — DevKit HQ',
    pageTitleResize: 'क्रॉप और रीसाइज़ — DevKit HQ',
    pageTitleWatermark: 'वॉटरमार्क — DevKit HQ',
    pageTitleImgBase64: 'इमेज से Base64 — DevKit HQ',
    pageTitlePalette: 'कलर पैलेट — DevKit HQ',
    pageTitleJson: 'JSON फॉर्मेटर — DevKit HQ',
    pageTitleBase64: 'Base64 कोडेक — DevKit HQ',
    pageTitleUrl: 'URL कोडेक — DevKit HQ',
    pageTitleTimestamp: 'टाइमस्टैम्प कन्वर्टर — DevKit HQ',
    pageTitleMarkdown: 'Markdown प्रीव्यू — DevKit HQ',
    pageTitleDomain: 'डोमेन खोज — DevKit HQ',
  },
  th: {
    navHome: 'หน้าแรก',
    navImageTools: 'เครื่องมือรูปภาพ',
    navDevTools: 'เครื่องมือพัฒนา',
    navDomain: 'ค้นหาโดเมน',
    heroBadge: '12 เครื่องมือออนไลน์ฟรี',
    heroTitle: 'เครื่องมือรูปภาพและโค้ด<br><span>ทุกอย่างในเบราว์เซอร์ของคุณ</span>',
    heroSub: 'ความเป็นส่วนตัวมาก่อน ทุกอย่างประมวลผลในเครื่อง กล่องเครื่องมือออนไลน์สำหรับนักพัฒนาและนักออกแบบ',
    heroCTA: 'เริ่มต้นใช้งาน',
    heroGithub: 'GitHub',
    secImage: 'เครื่องมือรูปภาพ',
    secImageSub: 'บีบอัด แปลง ลายน้ำ แยกพาเลท — ทั้งหมดผ่าน Canvas',
    secDev: 'เครื่องมือพัฒนา',
    secDevSub: 'จัดรูปแบบ เข้ารหัส ถอดรหัส — สิ่งจำเป็นประจำวันสำหรับนักพัฒนา',
    descCompress: 'การบีบอัดอัจฉริยะสำหรับ JPEG / PNG / WebP ประมวลผลแบบกลุ่ม ในเครื่อง',
    descConvert: 'แปลงระหว่าง JPEG, PNG, WebP พร้อมควบคุมคุณภาพและขนาด',
    descResize: 'ครอบตัดและปรับขนาดรูปภาพด้วยโปรแกรมแก้ไขภาพแบบโต้ตอบ',
    descWatermark: 'เพิ่มลายน้ำข้อความหรือรูปภาพเพื่อปกป้องงานของคุณ',
    descImgBase64: 'เข้ารหัสรูปภาพเป็นข้อความ Base64 คัดลอกในคลิกเดียว',
    descPalette: 'แยกสีเด่นจากรูปภาพใดๆ สร้างพาเลทสี',
    descJson: 'วาง JSON ที่ไม่เรียบร้อยและรับการจัดรูปแบบทันทีพร้อมไฮไลต์ข้อผิดพลาด',
    descBase64: 'เข้ารหัสและถอดรหัสข้อความเป็น/จาก Base64 รองรับ Unicode',
    descUrl: 'เข้ารหัสและถอดรหัส URL encodeURI / decodeURI',
    descTimestamp: 'แปลงระหว่าง Unix timestamp และวันที่ที่อ่านได้',
    descMarkdown: 'ดูตัวอย่าง Markdown สดพร้อมการแก้ไขแบบแบ่งหน้าจอ',
    descDomain: 'ค้นหาข้อมูล WHOIS สำหรับโดเมนใดๆ ตรวจสอบความพร้อมใช้งาน',
    toolCompress: 'บีบอัดรูปภาพ',
    toolConvert: 'แปลงรูปแบบ',
    toolResize: 'ครอบตัดและปรับขนาด',
    toolWatermark: 'ลายน้ำ',
    toolImgBase64: 'รูปภาพเป็น Base64',
    toolPalette: 'พาเลทสี',
    toolJson: 'จัดรูปแบบ JSON',
    toolBase64: 'ตัวเข้ารหัส Base64',
    toolUrl: 'ตัวเข้ารหัส URL',
    toolTimestamp: ' timestamp',
    toolMarkdown: 'ดูตัวอย่าง Markdown',
    toolDomain: 'ค้นหาโดเมน',
    taglineCompress: 'การบีบอัด JPEG / PNG / WebP อัจฉริยะ การประมวลผลทั้งหมดทำในเบราว์เซอร์ของคุณ',
    taglineConvert: 'แปลงระหว่างรูปแบบ JPEG, PNG, WebP พร้อมควบคุมคุณภาพและขนาด',
    taglineResize: 'เครื่องมือครอบตัดภาพพร้อมล็อคอัตราส่วนและขนาดที่กำหนดไว้ล่วงหน้า',
    taglineWatermark: 'เพิ่มลายน้ำข้อความหรือรูปภาพเพื่อปกป้องงานของคุณ',
    taglineImgBase64: 'เข้ารหัสรูปภาพเป็นข้อความ Base64 สำหรับฝังใน HTML/CSS',
    taglinePalette: 'อัปโหลดรูปภาพเพื่อแยกสีเด่นและพาเลทโดยอัตโนมัติ',
    taglineJson: 'วาง JSON เพื่อจัดรูปแบบหรือย่อทันทีพร้อมไฮไลต์บรรทัดข้อผิดพลาด คัดลอกในคลิกเดียว',
    taglineBase64: 'ตัวเข้ารหัสและถอดรหัส Base64 ออนไลน์ รองรับอักขระ Unicode',
    taglineUrl: 'การเข้ารหัสและถอดรหัส URL มาตรฐาน encodeURIComponent / decodeURIComponent',
    taglineTimestamp: 'แปลงระหว่าง Unix timestamp และวันที่ ตรวจจับวินาที/มิลลิวินาทีอัตโนมัติ',
    taglineMarkdown: 'ตัวแก้ไข Markdown สดพร้อมดูตัวอย่างแบบแบ่งหน้าจอ GitHub Flavored Markdown',
    taglineDomain: 'ค้นหาข้อมูล WHOIS สำหรับโดเมนใดๆ ตรวจสอบความพร้อมในการจดทะเบียน',
    footerImageTools: 'เครื่องมือรูปภาพ',
    footerDevTools: 'เครื่องมือพัฒนา',
    footerAbout: 'เกี่ยวกับ',
    footerAboutText: 'กล่องเครื่องมือออนไลน์ฟรีสำหรับนักพัฒนาและนักออกแบบ เครื่องมือทั้งหมดทำงานในเบราว์เซอร์ของคุณ — ไม่มีการอัปโหลดข้อมูลใดๆ',
    footerBottom: '© 2026 DevKit HQ · ประมวลผลในเครื่อง · ความเป็นส่วนตัวมาก่อน',
    footerMadeWith: 'สร้างด้วย',
    backHome: '← กลับหน้าแรก',
    footer: '© 2026 DevKit HQ · เครื่องมือทั้งหมดทำงานในเบราว์เซอร์ · ความปลอดภัยของข้อมูล',
    statTools: 'เครื่องมือ',
    statLocal: 'ประมวลผลในเครื่อง',
    statPrivacy: 'ไม่มีการอัปโหลดข้อมูล',
    themeDark: 'โหมดมืด',
    themeLight: 'โหมดสว่าง',
    copied: 'คัดลอกไปยังคลิปบอร์ดแล้ว',
    error: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
    processing: 'กำลังประมวลผล...',
    done: 'เสร็จสิ้น',
    pageTitle: 'DevKit HQ — เครื่องมือออนไลน์ฟรีสำหรับรูปภาพและโค้ด',
    pageTitleCompress: 'บีบอัดรูปภาพ — DevKit HQ',
    pageTitleConvert: 'แปลงรูปแบบ — DevKit HQ',
    pageTitleResize: 'ครอบตัดและปรับขนาด — DevKit HQ',
    pageTitleWatermark: 'ลายน้ำ — DevKit HQ',
    pageTitleImgBase64: 'รูปภาพเป็น Base64 — DevKit HQ',
    pageTitlePalette: 'พาเลทสี — DevKit HQ',
    pageTitleJson: 'จัดรูปแบบ JSON — DevKit HQ',
    pageTitleBase64: 'ตัวเข้ารหัส Base64 — DevKit HQ',
    pageTitleUrl: 'ตัวเข้ารหัส URL — DevKit HQ',
    pageTitleTimestamp: 'ตัวแปลงเวลา — DevKit HQ',
    pageTitleMarkdown: 'ดูตัวอย่าง Markdown — DevKit HQ',
    pageTitleDomain: 'ค้นหาโดเมน — DevKit HQ',
  },
  vi: {
    navHome: 'Trang chủ',
    navImageTools: 'Công cụ Ảnh',
    navDevTools: 'Công cụ Lập trình',
    navDomain: 'Tra cứu Tên miền',
    heroBadge: '12 Công cụ Trực tuyến Miễn phí',
    heroTitle: 'Công cụ ảnh và mã<br><span>tất cả trong trình duyệt</span>',
    heroSub: 'Quyền riêng tư là trên hết. Mọi thứ được xử lý cục bộ. Hộp công cụ trực tuyến cho nhà phát triển và nhà thiết kế.',
    heroCTA: 'Bắt đầu',
    heroGithub: 'GitHub',
    secImage: 'Công cụ Ảnh',
    secImageSub: 'Nén, chuyển đổi, đóng dấu, trích xuất bảng màu — tất cả qua Canvas',
    secDev: 'Công cụ Lập trình',
    secDevSub: 'Định dạng, mã hóa, giải mã — công cụ hàng ngày cho lập trình viên',
    descCompress: 'Nén thông minh cho JPEG / PNG / WebP. Xử lý hàng loạt, cục bộ.',
    descConvert: 'Chuyển đổi giữa JPEG, PNG, WebP với điều khiển chất lượng và kích thước.',
    descResize: 'Cắt và thay đổi kích thước ảnh với trình chỉnh sửa trực quan tương tác.',
    descWatermark: 'Thêm watermark văn bản hoặc hình ảnh để bảo vệ tác phẩm của bạn.',
    descImgBase64: 'Mã hóa hình ảnh thành văn bản Base64. Sao chép một cú nhấp.',
    descPalette: 'Trích xuất màu chủ đạo từ bất kỳ hình ảnh nào. Tạo bảng màu.',
    descJson: 'Dán JSON lộn xộn và nhận định dạng ngay lập tức với đánh dấu lỗi.',
    descBase64: 'Mã hóa và giải mã văn bản sang/từ Base64. Hỗ trợ Unicode.',
    descUrl: 'Mã hóa và giải mã URL. encodeURI / decodeURI.',
    descTimestamp: 'Chuyển đổi giữa Unix timestamp và ngày tháng dễ đọc.',
    descMarkdown: 'Xem trước Markdown trực tiếp với chỉnh sửa chia đôi màn hình.',
    descDomain: 'Tra cứu thông tin WHOIS cho bất kỳ tên miền nào. Kiểm tra khả dụng.',
    toolCompress: 'Nén ảnh',
    toolConvert: 'Chuyển đổi Định dạng',
    toolResize: 'Cắt và Đổi kích thước',
    toolWatermark: 'Watermark',
    toolImgBase64: 'Ảnh sang Base64',
    toolPalette: 'Bảng màu',
    toolJson: 'Định dạng JSON',
    toolBase64: 'Codec Base64',
    toolUrl: 'Codec URL',
    toolTimestamp: 'Timestamp',
    toolMarkdown: 'Xem trước Markdown',
    toolDomain: 'Tra cứu Tên miền',
    taglineCompress: 'Nén JPEG / PNG / WebP thông minh. Tất cả xử lý được thực hiện cục bộ trong trình duyệt của bạn.',
    taglineConvert: 'Chuyển đổi giữa các định dạng JPEG, PNG, WebP với điều khiển chất lượng và kích thước.',
    taglineResize: 'Công cụ cắt ảnh trực quan với khóa tỷ lệ và kích thước có sẵn.',
    taglineWatermark: 'Thêm watermark văn bản hoặc hình ảnh để bảo vệ tác phẩm của bạn.',
    taglineImgBase64: 'Mã hóa hình ảnh thành văn bản Base64 để nhúng vào HTML/CSS.',
    taglinePalette: 'Tải lên hình ảnh để tự động trích xuất màu chủ đạo và bảng màu.',
    taglineJson: 'Dán JSON để định dạng hoặc rút gọn ngay lập tức với đánh dấu dòng lỗi. Sao chép một cú nhấp.',
    taglineBase64: 'Mã hóa và giải mã Base64 trực tuyến. Hỗ trợ ký tự Unicode.',
    taglineUrl: 'Mã hóa và giải mã URL. Chuẩn encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Chuyển đổi giữa Unix timestamp và ngày tháng. Tự động phát hiện giây/mili giây.',
    taglineMarkdown: 'Trình chỉnh sửa Markdown trực tiếp với xem trước chia đôi màn hình. GitHub Flavored Markdown.',
    taglineDomain: 'Tra cứu thông tin WHOIS cho bất kỳ tên miền nào. Kiểm tra khả dụng đăng ký.',
    footerImageTools: 'Công cụ Ảnh',
    footerDevTools: 'Công cụ Lập trình',
    footerAbout: 'Giới thiệu',
    footerAboutText: 'Hộp công cụ trực tuyến miễn phí cho nhà phát triển và nhà thiết kế. Tất cả công cụ chạy cục bộ trong trình duyệt của bạn — không có dữ liệu nào được tải lên.',
    footerBottom: '© 2026 DevKit HQ · Xử lý cục bộ · Quyền riêng tư là trên hết',
    footerMadeWith: 'Tạo bằng',
    backHome: '← Quay về Trang chủ',
    footer: '© 2026 DevKit HQ · Tất cả công cụ chạy cục bộ trong trình duyệt · Bảo mật',
    statTools: 'Công cụ',
    statLocal: 'Xử lý Cục bộ',
    statPrivacy: 'Không Tải lên Dữ liệu',
    themeDark: 'Chế độ tối',
    themeLight: 'Chế độ sáng',
    copied: 'Đã sao chép vào clipboard',
    error: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    processing: 'Đang xử lý...',
    done: 'Hoàn tất',
    pageTitle: 'DevKit HQ — Công cụ Trực tuyến Miễn phí cho Ảnh và Mã',
    pageTitleCompress: 'Nén ảnh — DevKit HQ',
    pageTitleConvert: 'Chuyển đổi Định dạng — DevKit HQ',
    pageTitleResize: 'Cắt và Đổi kích thước — DevKit HQ',
    pageTitleWatermark: 'Watermark — DevKit HQ',
    pageTitleImgBase64: 'Ảnh sang Base64 — DevKit HQ',
    pageTitlePalette: 'Bảng màu — DevKit HQ',
    pageTitleJson: 'Định dạng JSON — DevKit HQ',
    pageTitleBase64: 'Codec Base64 — DevKit HQ',
    pageTitleUrl: 'Codec URL — DevKit HQ',
    pageTitleTimestamp: 'Chuyển đổi Timestamp — DevKit HQ',
    pageTitleMarkdown: 'Xem trước Markdown — DevKit HQ',
    pageTitleDomain: 'Tra cứu Tên miền — DevKit HQ',
  },
  tr: {
    navHome: 'Ana Sayfa',
    navImageTools: 'Görsel Araçları',
    navDevTools: 'Geliştirici Araçları',
    navDomain: 'Alan Adı Sorgulama',
    heroBadge: '12 Ücretsiz Çevrimiçi Araç',
    heroTitle: 'Görsel ve kod araçları<br><span>hepsi tarayıcınızda</span>',
    heroSub: 'Gizlilik önceliklidir. Her şey yerel olarak işlenir. Geliştiriciler ve tasarımcılar için çevrimiçi araç kutusu.',
    heroCTA: 'Başlayın',
    heroGithub: 'GitHub',
    secImage: 'Görsel Araçları',
    secImageSub: 'Sıkıştır, dönüştür, filigran ekle, palet çıkar — hepsi Canvas ile',
    secDev: 'Geliştirici Araçları',
    secDevSub: 'Biçimlendir, kodla, kodu çöz — geliştiriciler için günlük temel araçlar',
    descCompress: 'JPEG / PNG / WebP için akıllı sıkıştırma. Toplu işleme, yerel.',
    descConvert: 'JPEG, PNG, WebP arasında kalite ve boyut kontrolleriyle dönüştürün.',
    descResize: 'Etkileşimli görsel düzenleyici ile görüntüleri kırpın ve yeniden boyutlandırın.',
    descWatermark: 'Çalışmanızı korumak için metin veya görüntü filigranı ekleyin.',
    descImgBase64: 'Görüntüleri Base64 metne kodlayın. Tek tıkla kopyalayın.',
    descPalette: 'Herhangi bir görüntüden baskın renkleri çıkarın. Paletler oluşturun.',
    descJson: 'Dağınık JSON yapıştırın ve hata vurgulama ile anında biçimlendirme alın.',
    descBase64: 'Metni Base64e/Base64ten kodlayın ve çözün. Unicode destekler.',
    descUrl: 'URL kodlama ve çözme. encodeURI / decodeURI.',
    descTimestamp: 'Unix zaman damgaları ve okunabilir tarihler arasında dönüştürün.',
    descMarkdown: 'Bölünmüş panel düzenleme ile canlı Markdown önizlemesi.',
    descDomain: 'Herhangi bir alan adı için WHOIS bilgilerini sorgulayın. Kullanılabilirliği kontrol edin.',
    toolCompress: 'Görsel Sıkıştırma',
    toolConvert: 'Biçim Dönüştürme',
    toolResize: 'Kırp ve Yeniden Boyutlandır',
    toolWatermark: 'Filigran',
    toolImgBase64: 'Görselden Base64e',
    toolPalette: 'Renk Paleti',
    toolJson: 'JSON Biçimlendirici',
    toolBase64: 'Base64 Kodlayıcı',
    toolUrl: 'URL Kodlayıcı',
    toolTimestamp: 'Zaman Damgası',
    toolMarkdown: 'Markdown Önizleme',
    toolDomain: 'Alan Adı Sorgulama',
    taglineCompress: 'Akıllı JPEG / PNG / WebP sıkıştırma. Tüm işlemler tarayıcınızda yerel olarak yapılır.',
    taglineConvert: 'JPEG, PNG, WebP biçimleri arasında kalite ve boyut kontrolleriyle dönüştürün.',
    taglineResize: 'En boy oranı kilidi ve hazır boyutlarla görsel kırpma aracı.',
    taglineWatermark: 'Çalışmanızı korumak için metin veya görüntü filigranı ekleyin.',
    taglineImgBase64: 'HTML/CSS içine gömmek için görüntüleri Base64 metne kodlayın.',
    taglinePalette: 'Baskın renkleri ve paletleri otomatik olarak çıkarmak için bir görüntü yükleyin.',
    taglineJson: 'Anında biçimlendirme veya küçültme için JSON yapıştırın. Hata satırı vurgulama. Tek tıkla kopyalama.',
    taglineBase64: 'Çevrimiçi Base64 kodlayıcı ve çözücü. Unicode karakterleri destekler.',
    taglineUrl: 'URL kodlama ve çözme. Standart encodeURIComponent / decodeURIComponent.',
    taglineTimestamp: 'Unix zaman damgaları ve tarihler arasında dönüştürün. Saniye/milisaniye otomatik algılama.',
    taglineMarkdown: 'Bölünmüş panel önizlemeli canlı Markdown düzenleyici. GitHub Flavored Markdown.',
    taglineDomain: 'Herhangi bir alan adı için WHOIS bilgilerini sorgulayın. Kayıt kullanılabilirliğini kontrol edin.',
    footerImageTools: 'Görsel Araçları',
    footerDevTools: 'Geliştirici Araçları',
    footerAbout: 'Hakkında',
    footerAboutText: 'Geliştiriciler ve tasarımcılar için ücretsiz çevrimiçi araç kutusu. Tüm araçlar tarayıcınızda yerel olarak çalışır — hiçbir veri yüklenmez.',
    footerBottom: '© 2026 DevKit HQ · Yerel işleme · Gizlilik önceliklidir',
    footerMadeWith: 'ile yapıldı',
    backHome: '← Ana Sayfaya Dön',
    footer: '© 2026 DevKit HQ · Tüm araçlar tarayıcıda yerel olarak çalışır · Gizlilik güvenli',
    statTools: 'Araç',
    statLocal: 'Yerel İşleme',
    statPrivacy: 'Veri Yüklenmez',
    themeDark: 'Karanlık mod',
    themeLight: 'Aydınlık mod',
    copied: 'Panoya kopyalandı',
    error: 'Bir şeyler yanlış gitti. Lütfen tekrar deneyin.',
    processing: 'İşleniyor...',
    done: 'Tamamlandı',
    pageTitle: 'DevKit HQ — Görseller ve Kod için Ücretsiz Çevrimiçi Araçlar',
    pageTitleCompress: 'Görsel Sıkıştırma — DevKit HQ',
    pageTitleConvert: 'Biçim Dönüştürme — DevKit HQ',
    pageTitleResize: 'Kırp ve Yeniden Boyutlandır — DevKit HQ',
    pageTitleWatermark: 'Filigran — DevKit HQ',
    pageTitleImgBase64: 'Görselden Base64e — DevKit HQ',
    pageTitlePalette: 'Renk Paleti — DevKit HQ',
    pageTitleJson: 'JSON Biçimlendirici — DevKit HQ',
    pageTitleBase64: 'Base64 Kodlayıcı — DevKit HQ',
    pageTitleUrl: 'URL Kodlayıcı — DevKit HQ',
    pageTitleTimestamp: 'Zaman Damgası Dönüştürücü — DevKit HQ',
    pageTitleMarkdown: 'Markdown Önizleme — DevKit HQ',
    pageTitleDomain: 'Alan Adı Sorgulama — DevKit HQ',
  },
};


// Date locale mapping for domain-lookup and timestamp
const LOCALE_MAP = {
  zh: 'zh-CN', en: 'en-US', ja: 'ja-JP', ko: 'ko-KR',
  ru: 'ru-RU', pt: 'pt-BR', es: 'es-ES', fr: 'fr-FR',
  de: 'de-DE', it: 'it-IT', ar: 'ar-SA', hi: 'hi-IN',
  th: 'th-TH', vi: 'vi-VN', tr: 'tr-TR'
};
function getLocale() { return LOCALE_MAP[lang] || 'en-US'; }
// ===== Language Management =====
let lang = localStorage.getItem('dk_lang') || (navigator.language.startsWith('zh') ? 'zh' : 'en');
let dark = localStorage.getItem('dk_theme') === null ? true : localStorage.getItem('dk_theme') === 'dark';

function t(key) {
  return I18N[lang][key] || I18N['en'][key] || key;
}

function applyI18n() {
  document.querySelectorAll('[data-i]').forEach(el => {
    const key = el.dataset.i;
    const val = I18N[lang][key] !== undefined ? I18N[lang][key] : (I18N['en'][key] || key);
    if (key === 'heroTitle') {
      el.innerHTML = val;
    } else {
      el.textContent = val;
    }
  });
  document.querySelectorAll('[data-i-placeholder]').forEach(el => {
    const key = el.dataset.iPlaceholder;
    const val = I18N[lang][key] !== undefined ? I18N[lang][key] : (I18N['en'][key] || key);
    if (val) el.placeholder = val;
  });
  document.querySelectorAll('[data-i-alt]').forEach(el => {
    const key = el.dataset.iAlt;
    const val = I18N[lang][key] !== undefined ? I18N[lang][key] : (I18N['en'][key] || key);
    if (val) el.alt = val;
  });
  // Update language button flag
  const langBtn = document.getElementById('langBtn');
  if (langBtn) {
    const currLang = LANGUAGES.find(l => l.code === lang);
    if (currLang) langBtn.textContent = currLang.flag;
  }
  // RTL handling
  const currLang = LANGUAGES.find(l => l.code === lang);
  if (currLang && currLang.rtl) {
    document.documentElement.setAttribute('dir', 'rtl');
  } else {
    document.documentElement.removeAttribute('dir');
  }
  updatePageMeta();
}

function setLang(code) {
  if (!I18N[code]) return;
  lang = code;
  localStorage.setItem('dk_lang', lang);
  applyI18n();
  // Close dropdown
  const dd = document.getElementById('langDropdown');
  if (dd) dd.classList.remove('show');
}

function updatePageMeta() {
  const titleEl = document.querySelector('[data-i-title]');
  if (titleEl) {
    const key = titleEl.dataset.iTitle;
    const title = I18N[lang][key] || I18N['en'][key];
    if (title) document.title = title;
  }
}

function renderLangPicker() {
  const currLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[1];
  let html = '<button class="lang-btn" id="langBtn" title="' + currLang.nativeName + '">' + currLang.flag + '</button>';
  html += '<div class="lang-dropdown" id="langDropdown">';
  LANGUAGES.forEach(l => {
    html += '<button class="lang-option' + (l.code === lang ? ' active' : '') + '" data-lang="' + l.code + '">' + l.flag + ' ' + l.nativeName + '</button>';
  });
  html += '</div>';
  return html;
}

// ===== Theme =====
function applyTheme() {
  if (dark) {
    document.documentElement.removeAttribute('data-theme');
  } else {
    document.documentElement.setAttribute('data-theme', 'light');
  }
  const themeBtn = document.getElementById('themeBtn');
  if (themeBtn) themeBtn.textContent = dark ? '☀️' : '🌙';
  if (themeBtn) themeBtn.title = dark ? t('themeLight') : t('themeDark');
}

function toggleTheme() {
  dark = !dark;
  localStorage.setItem('dk_theme', dark ? 'dark' : 'light');
  applyTheme();
}

// ===== Nav =====
function renderNav(currentPage) {
  const nav = document.getElementById('nav');
  if (!nav) return;
  nav.innerHTML = ''
    + '<div class="nav-inner">'
    + '<a href="/" class="nav-logo">'
    + '<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">'
    + '<rect width="28" height="28" rx="7" fill="url(#dkGrad)"/>'
    + '<defs>'
    + '<linearGradient id="dkGrad" x1="0" y1="0" x2="28" y2="28">'
    + '<stop offset="0%" stop-color="#3b82f6"/>'
    + '<stop offset="100%" stop-color="#6366f1"/>'
    + '</linearGradient>'
    + '</defs>'
    + '<text x="14" y="19.5" text-anchor="middle" font-family="-apple-system,BlinkMacSystemFont,\'Segoe UI\',sans-serif" font-size="15" font-weight="800" fill="#fff" letter-spacing="-0.5">DK</text>'
    + '</svg>'
    + 'DevKit'
    + '</a>'
    + '<div class="nav-links">'
    + '<a href="/" class="nav-link ' + (currentPage === 'home' ? 'active' : '') + '" data-i="navHome">' + t('navHome') + '</a>'
    + '<a href="/tools/compress.html" class="nav-link ' + (currentPage === 'image' ? 'active' : '') + '" data-i="navImageTools">' + t('navImageTools') + '</a>'
    + '<a href="/tools/json-formatter.html" class="nav-link ' + (currentPage === 'dev' ? 'active' : '') + '" data-i="navDevTools">' + t('navDevTools') + '</a>'
    + '<a href="/tools/domain-lookup.html" class="nav-link ' + (currentPage === 'domain' ? 'active' : '') + '" data-i="navDomain">' + t('navDomain') + '</a>'
    + '</div>'
    + '<div class="nav-right">'
    + '<div class="lang-wrap">'
    + renderLangPicker()
    + '</div>'
    + '<button class="nav-icon" id="themeBtn" title="' + (dark ? t('themeLight') : t('themeDark')) + '">' + (dark ? '☀️' : '🌙') + '</button>'
    + '<button class="nav-hamburger" id="hamburgerBtn" aria-label="Menu">'
    + '<span></span><span></span><span></span>'
    + '</button>'
    + '</div>'
    + '</div>'
    + '<div class="mobile-menu" id="mobileMenu">'
    + '<a href="/" class="' + (currentPage === 'home' ? 'active' : '') + '" data-i="navHome">' + t('navHome') + '</a>'
    + '<a href="/tools/compress.html" class="' + (currentPage === 'image' ? 'active' : '') + '" data-i="navImageTools">' + t('navImageTools') + '</a>'
    + '<a href="/tools/json-formatter.html" class="' + (currentPage === 'dev' ? 'active' : '') + '" data-i="navDevTools">' + t('navDevTools') + '</a>'
    + '<a href="/tools/domain-lookup.html" class="' + (currentPage === 'domain' ? 'active' : '') + '" data-i="navDomain">' + t('navDomain') + '</a>'
    + '</div>'
  ;

  // Language button
  document.getElementById('langBtn').addEventListener('click', (e) => {
    e.stopPropagation();
    document.getElementById('langDropdown').classList.toggle('show');
  });
  // Language options
  document.querySelectorAll('.lang-option').forEach(btn => {
    btn.addEventListener('click', () => setLang(btn.dataset.lang));
  });
  // Close dropdown on outside click
  document.addEventListener('click', () => {
    const dd = document.getElementById('langDropdown');
    if (dd) dd.classList.remove('show');
  });

  // Theme button
  document.getElementById('themeBtn').addEventListener('click', toggleTheme);

  // Hamburger menu
  const hamburger = document.getElementById('hamburgerBtn');
  const mobileMenu = document.getElementById('mobileMenu');
  hamburger.addEventListener('click', () => {
    hamburger.classList.toggle('open');
    mobileMenu.classList.toggle('show');
  });
  mobileMenu.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      hamburger.classList.remove('open');
      mobileMenu.classList.remove('show');
    });
  });
  document.addEventListener('click', (e) => {
    if (!hamburger.contains(e.target) && !mobileMenu.contains(e.target)) {
      hamburger.classList.remove('open');
      mobileMenu.classList.remove('show');
    }
  });
}

// ===== Toast =====
function toast(msg, duration = 2500) {
  let el = document.getElementById('toast');
  if (!el) {
    el = document.createElement('div');
    el.id = 'toast';
    el.className = 'toast';
    document.body.appendChild(el);
  }
  el.textContent = msg;
  el.classList.add('show');
  clearTimeout(el._timer);
  el._timer = setTimeout(() => el.classList.remove('show'), duration);
}

// ===== Utilities =====
function formatBytes(bytes) {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(i > 0 ? 1 : 0)) + ' ' + sizes[i];
}

function copyToClipboard(text) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text).then(() => toast(t('copied'))).catch(() => fallbackCopy(text));
  } else {
    fallbackCopy(text);
  }
}

function fallbackCopy(text) {
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  try { document.execCommand('copy'); toast(t('copied')); } catch (e) { toast(t('error')); }
  document.body.removeChild(ta);
}

function debounce(fn, ms = 300) {
  let timer;
  return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); };
}

// ===== Init =====
document.addEventListener('DOMContentLoaded', () => {
  applyTheme();
  applyI18n();

  // Vercel Analytics
  const va = document.createElement('script');
  va.defer = true;
  va.src = '/_vercel/insights/script.js';
  document.head.appendChild(va);
});
